### ISSUE TITLE
Reduce `MAX_EMBEDDING_DIM` constant from `4096` to `1536`

### ISSUE THREAD

**Issue by sarahwooders** [letta-ai/letta#1028]
We probably do not need to support embedding dimensions of more than 1536, and having an embedding dimention of larger than 2000 means we can no longer build a Postgres index using pgvector. 

Making this change will break people's existing archival memory tables, so will need to include an update to migration code (`migrate.py`).

**Comment by jward92** [comment]
@sarahwooders https://github.com/cpacker/MemGPT/pull/1603 FYI - ready for review. Thanks!
