### ISSUE TITLE
cannot import name 'Document' from 'llama_index.core' (unknown location)

### ISSUE THREAD

**Issue by AbrahamQll** [letta-ai/letta#1078]
**Describe the bug**
When I want to run "memgpt run" or "memgpt configure" on my Windows 10 X64 machine, using python 3.11.7 I get the following error:

`memgpt run
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\memgpt.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\memgpt\__init__.py", line 3, in <module>
    from memgpt.client.client import create_client
  File "C:\Program Files\Python311\Lib\site-packages\memgpt\client\client.py", line 8, in <module>
    from memgpt.cli.cli import QuickstartChoice
  File "C:\Program Files\Python311\Lib\site-packages\memgpt\cli\cli.py", line 26, in <module>
    from memgpt.agent import Agent, save_agent
  File "C:\Program Files\Python311\Lib\site-packages\memgpt\agent.py", line 15, in <module>
    from memgpt.persistence_manager import LocalStateManager
  File "C:\Program Files\Python311\Lib\site-packages\memgpt\persistence_manager.py", line 5, in <module>
    from memgpt.memory import (
  File "C:\Program Files\Python311\Lib\site-packages\memgpt\memory.py", line 10, in <module>
    from memgpt.embeddings import embedding_model, query_embedding, parse_and_chunk_text
  File "C:\Program Files\Python311\Lib\site-packages\memgpt\embeddings.py", line 14, in <module>
    from llama_index.core import Document as LlamaIndexDocument
ImportError: cannot import name 'Document' from 'llama_index.core' (unknown location)`

**Please describe your setup**
- [ ] How did you install memgpt?
  - `pip install pymemgpt` and `pip install pymemgpt[postgres]`
- [ ] Describe your setup
  - What's your OS (Windows/MacOS/Linux)? Windows 10 X64 
  - How are you running `memgpt`? `cmd.exe`

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.

---
I am using OpenAI

**Comment by quantumalchemy** [comment]
getting same in linux (debian) pip install pymemgpt -U  
pymemgpt v0.3.4

**Comment by Minktong** [comment]
I have just installed the package using the command `pip install -U pymemgpt` and I am getting the same error.

**Comment by yekamu** [comment]
same here. I install with pip -e. then I update llama-index to 0.1-14, same error before and after the update

**Comment by jkothamb-sai** [comment]
Had to make following changes and install from source i.e `pip install -e "."`
`git diff
diff --git a/memgpt/data_sources/connectors.py b/memgpt/data_sources/connectors.py
index 00d93d8..fad929f 100644
--- a/memgpt/data_sources/connectors.py
+++ b/memgpt/data_sources/connectors.py
@@ -6,7 +6,7 @@ from memgpt.data_types import Document, Passage
 
 from typing import List, Iterator, Dict, Tuple, Optional
 import typer
-from llama_index.core import Document as LlamaIndexDocument
+from llama_index.core.schema import Document as LlamaIndexDocument
 
 
 class DataConnector:
@@ -103,7 +103,7 @@ class DirectoryConnector(DataConnector):
             assert self.input_directory is not None, "Must provide input directory if recursive is True."
 
     def generate_documents(self) -> Iterator[Tuple[str, Dict]]:  # -> Iterator[Document]:
-        from llama_index.core import SimpleDirectoryReader
+        from llama_index.core.readers import SimpleDirectoryReader
 
         if self.input_directory is not None:
             reader = SimpleDirectoryReader(
diff --git a/memgpt/embeddings.py b/memgpt/embeddings.py
index ee7d4b8..5792641 100644
--- a/memgpt/embeddings.py
+++ b/memgpt/embeddings.py
@@ -11,7 +11,7 @@ from memgpt.constants import MAX_EMBEDDING_DIM, EMBEDDING_TO_TOKENIZER_MAP, EMBE
 
 # from llama_index.core.base.embeddings import BaseEmbedding
 from llama_index.core.node_parser import SentenceSplitter
-from llama_index.core import Document as LlamaIndexDocument
+from llama_index.core.schema import Document as LlamaIndexDocument
 
 # from llama_index.core.base.embeddings import BaseEmbedding
 # from llama_index.core.embeddings import BaseEmbedding`

**Comment by sarahwooders** [comment]
Is this still an issue on the latest version?

**Comment by vivekagb** [comment]
I am still facing this. Just updated from version 0.3.0 to 0.3.14

**Comment by lastrosade** [comment]
I can confirm that this is still an issue on latest.
