### ISSUE TITLE
The more expensive "default" gpt-4-0613 used even if gpt4-1106-preview is configured

### ISSUE THREAD

**Issue by distributev** [letta-ai/letta#1153]
I played yesterday with MemGPT and I really like what I saw. 

However I came into this issue.

![image](https://github.com/cpacker/MemGPT/assets/19224635/c88368a5-6a62-4d16-bc54-181304322f41)

another thing is that after all the credits from the account were consumed MemGPT, instead of simply saying somethign like "Out of Credit, please fill your account" it says 

"Rate Limit" Retry in X seconds which is obviously it is pointless to retry when out of credit. 

It is also confusing for the user as it will not know what is happening.

**Comment by distributev** [comment]
More details - the agents which I created today do indeed use the new (less) expensive model of GPT-4-1106-preview

Yesterday I was playing with an older agent which was created most likely when the configured model was GPT-4-0613

Which makes me think is that the agents are using the model which was configured (active) at the time of their creation and if
you change the model later in the configuration file this will not have any effect for the existing agents? Is it working like that?

If it is working indeed like that this is fine, but it should be documented somewhere otherwise people will change the model for a less expensive one and then they will realize that their change did not take any effect.

**Comment by bitsnaps** [comment]
I've been using some limited LLM providers and have occasionally encountered rate limit errors. I believe a useful feature to add would be the exposure of a `refresh_per_second` [parameter](https://github.com/cpacker/MemGPT/blob/c29214526a2adee22414b8a8739458d98665a0c8/memgpt/streaming_interface.py#L268) or other similar rate limit feature to avoid throttling. This would allow users to adjust the rate of requests to the API, and may fixes #1106 ?
