### ISSUE TITLE
Make `/admin/users` route paginated

### ISSUE THREAD

**Issue by sarahwooders** [letta-ai/letta#1156]
This will cause issues for a large number of users without pagination https://memgpt.readme.io/reference/get_all_users_admin_users_get

**Comment by ajanitshimanga** [comment]
Hi! I'd like to pick up this issue. Is there need for a particular type of pagination (Offset-Based Pagination / Keyset pagination)?

**Comment by sarahwooders** [comment]
It would be great if we could do something similar to how we do paginated retrieval for agent messages: 
https://github.com/cpacker/MemGPT/blob/main/memgpt/server/rest_api/agents/message.py#L94

The purpose of the endpoint is so that when we eventually have an admin panel, the administrator and page through the users, as there may be a large number of users in total.

**Comment by ajanitshimanga** [comment]
@sarahwooders Can this be closed now?
