### ISSUE TITLE
MemGPT server does not obey configuration

### ISSUE THREAD

**Issue by moritz-linss** [letta-ai/letta#1188]
**Describe the bug**
I am currently switching over to MemGPT server, but when using memgpt through the server both the chroma and embedding configurations are not picked up and instead the defaults are used. Chroma does not use http storage and embedding does not use the proper model.

**Please describe your setup**
- [ ] How did you install memgpt?
  - `pip install pymemgpt` (inside a conda environment)
- [ ] Describe your setup
  - MacOS or Ubuntu
  - Python 3.11
  - Running `memgpt server` embedded inside a python application as daemon thread.

**Screenshots**
---

**Additional context**
I am not configuring memgpt through `memgpt configure` but insted set up a configuration from a .json file which is then saved. I used this with zero problems since version 0.2.11.
As soon as archival storage should be inserted, the embedding process uses `text-embedding-ada-002` instead of `text-embedding-3-small` and afterwards writes to local storage in the `/.memgpt/chroma` directory. There is no request going through to the Chroma database I have been using successfully from the start with every previous version. I have tried different configurations, but it always reverts back to default.
_EDIT:_ I tried this with cli `memgpt configure` and `memgpt server`on both OS but it yields the same result as above.

**MemGPT Config**
```
[defaults]
preset = memgpt_chat
human = listener

[model]
model = gpt-4-1106-preview
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
context_window = 128000

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_model = text-embedding-3-small
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /Users/moritz-linss/.memgpt/chroma
uri = http://localhost:8080

[recall_storage]
type = sqlite
path = /Users/moritz-linss/.memgpt

[metadata_storage]
type = sqlite
path = /Users/moritz-linss/.memgpt

[version]
memgpt_version = 0.3.7
```

**Comment by ucekmez** [comment]
https://github.com/cpacker/MemGPT/pull/1194 this pr fixes it

**Comment by moritz-linss** [comment]
This seems to be related to Azure and should fix a hard coding there, but the openai endpoint should already be configured correctly. With #1194 it still keeps defaulting. I am not sure if this actually addresses the root cause as I suspect this is an issue with loading the correct configuration for the server, though I am currently unable to locate it.

**Comment by ucekmez** [comment]
checked again and you are right. heading back

**Comment by moritz-linss** [comment]
To folllow up: this issue still persists with version 0.3.8.

**Comment by moritz-linss** [comment]
Another follow up: the issue still presists with 0.3.9.

**Comment by sarahwooders** [comment]
@moritz-linss sorry for the delayed response - could you please post an example of at what point (e.g. from the CLI? from the Python API) you see the wrong endpoint getting called? 

We recently removed the default embeddings from the config, so if you could also try the most recent version that would be great.

**Comment by moritz-linss** [comment]
Hi @sarahwooders no problem. I just upgraded to version 0.3.14 and now the configuration it returns is now completely weird:
```
[defaults]
preset = memgpt_chat
persona = sam_pov
human = listener

[model]
model = gpt-4-1106-preview
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
context_window = 128000

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_model = text-embedding-3-small
embedding_dim = 1536
embedding_chunk_size = 512

[archival_storage]
type = chroma
path = /Users/moritz.linss/.memgpt/chroma
uri = postgresql+pg8000://memgpt:memgpt@localhost:5432/memgpt

[recall_storage]
type = sqlite
path = /Users/moritz.linss/.memgpt
uri = postgresql+pg8000://memgpt:memgpt@localhost:5432/memgpt

[metadata_storage]
type = sqlite
path = /Users/moritz.linss/.memgpt
uri = postgresql+pg8000://memgpt:memgpt@localhost:5432/memgpt

[version]
memgpt_version = 0.3.14

[client]
anon_clientid = 000000000000000000008e147dab19c1
```

The configuration i try to set is as follows (I use the `set_config_from_dict` function):
```
{
    "preset": "memgpt_chat",
    "persona": null,
    "human": "listener",
    "context_window": 128000,
    "model": "gpt-4-1106-preview",
    "model_endpoint_type": "openai",
    "model_endpoint": "https://api.openai.com/v1",
    "model_wrapper": null,
    "embedding_endpoint_type": "openai",
    "embedding_endpoint": "https://api.openai.com/v1",
    "embedding_model": "text-embedding-3-small",
    "embedding_dim": 1536,
    "embedding_chunk_size": 512,
    "archival_storage_type": "chroma",
    "archival_storage_path": null,
    "archival_storage_uri": "http://localhost:8080"
}
```

I am honestly quite confused. Yes, there is another postgres database which is used in another part of the application, but it should definitely not appear in the MemGPT config. I do not know where the server actually pulls the postgres configuration from. Really odd behaviour.

The output i received from debugging for the embedding was `Request options: {'method': 'post', 'url': '/embeddings', 'files': None, 'post_parser': <function Embeddings.create.<locals>.parser at 0x30bf262a0>, 'json_data': {'input': ['...'], 'model': 'text-embedding-ada-002', 'encoding_format': 'base64'}}`.

I hope this helps in some way. I am trying to get it running again to determine what the root cause of all this is.

**Comment by moritz-linss** [comment]
The issue seems to be with the configuration. `set_config_from_dict` actually works fine:
```
Skipping new config preset: memgpt_chat == memgpt_chat
Replacing config persona: sam_pov -> None
Replacing config human: basic -> listener
Skipping new config archival_storage_type: chroma == chroma
Replacing config archival_storage_path: /Users/moritz.linss/.memgpt/chroma -> None
Replacing config archival_storage_uri: None -> localhost:8080
Setting new config embedding_model: text-embedding-3-small
Setting new config embedding_dim: 1536
Setting new config embedding_chunk_size: 512
Setting new config embedding_endpoint: https://api.openai.com/v1
Setting new config embedding_endpoint_type: openai
Setting new config model: gpt-4-1106-preview
Setting new config model_endpoint: https://api.openai.com/v1
Setting new config model_endpoint_type: openai
Setting new config model_wrapper: None
Setting new config context_window: 128000
```
...but this never arrives in the memgpt config. Some things are reverted or replaced, some are correct, some mixed up (as seen above in my last comment).

**Comment by moritz-linss** [comment]
Another observation: When installing via pip, the following passages are missing. Not sure if the first one is relevant in any way, but the second one seems pretty important.
https://github.com/cpacker/MemGPT/blob/29e9db9c37c204494827c1465ad11a177852b53d/memgpt/server/rest_api/server.py#L41-L49
https://github.com/cpacker/MemGPT/blob/29e9db9c37c204494827c1465ad11a177852b53d/memgpt/server/rest_api/server.py#L56-L57

**Comment by moritz-linss** [comment]
Going through revent issues this seems to be related to https://github.com/cpacker/MemGPT/issues/1362 and https://github.com/cpacker/MemGPT/issues/1371

**Comment by moritz-linss** [comment]
Is there any update on this yet @sarahwooders ? I saw some fixes regarding the postgres etc. - I would suggest that i try and check if this still persits in the course of the week, but I still really hope this gets tackled soon and I can't believe i would be the only one having these issues.

**Comment by sarahwooders** [comment]
You're running the server with `memgpt server`, not `docker compose up`, right? I'm not sure why `export MEMGPT_SERVER_PASS=...` isn't working... 

The chroma HTTP server support was added a very long time ago, and so I wouldn't be surprised if its broken. Are you using a hosted chroma? 

Since there are a couple issues, could you maybe DM me on discord so we can go over your setup in a call?
