### ISSUE TITLE
Attaching data to agents is not working as expected

### ISSUE THREAD

**Issue by adarsh-trenser** [letta-ai/letta#1240]
**Describe the bug**
Unable attaching a data source to agent's archival memory to access.
![image](https://github.com/cpacker/MemGPT/assets/117730381/14dfb10a-1ea8-4102-9b63-428663731f6f)

I have attached data using following command:
`memgpt load directory --name treatment --input-files=treatment.pdf`
But not able to get source id, after execution.

**Please describe your setup**
- [ ] How did you install memgpt?
  -  `git clone`
- [ ] Describe your setup
  - What's your OS : Windows
  - Running `memgpt` in Python 3.11

**Screenshots**
![image](https://github.com/cpacker/MemGPT/assets/117730381/cee5169d-ff70-4d17-9669-7b1038b10efb)

**MemGPT Config**
[defaults]
preset = memgpt_chat
persona = sam_simple_pov_gpt35
human = cs_phd

[model]
model = gpt-3.5-turbo
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
context_window = 4096

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_model = text-embedding-ada-002
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = C:\Users\1267\.memgpt\chroma

[recall_storage]
type = sqlite
path = C:\Users\1267\.memgpt

[metadata_storage]
type = sqlite
path = C:\Users\1267\.memgpt

[version]
memgpt_version = 0.3.8

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000

---

**Comment by atroiano-glue** [comment]
Any progress on this Bug?

**Comment by sarahwooders** [comment]
Thanks for reporting this! The documentation is outdated and the client API should actually be: 
```
client.attach_source_to_agent(source_id: uuid.UUID, agent_id: uuid.UUID)
```
You can get available sources and their IDs with `client.list_sources()`. 

This is admittedly not the best API, so we might change is so that you can also attach by name.
