### ISSUE TITLE
Nonetype object has no attribute model : AUTOGEN + MEMGPT

### ISSUE THREAD

**Issue by Harichandra-Prasath** [letta-ai/letta#1344]
Autogen + memgpt results in `Nonetype object has no attribute model` through `create_memgpt_autogen_agent_from_config`

**Please describe your setup**
- [ ] How did you install memgpt?
  - `pip install pymemgpt`
- [ ] Describe your setup
  - google colab?

**Screenshots**
![image](https://github.com/cpacker/MemGPT/assets/129069095/6a62ec84-4c38-4473-9c0d-17960189af94)

**To reproduce**
Just try to run the official example given by memgpt for autogen + memgpt

 link - https://colab.research.google.com/github/cpacker/MemGPT/blob/main/memgpt/autogen/examples/memgpt_coder_autogen.ipynb#scrollTo=flVCXXKirZ-c

**Comment by dbwrangler** [comment]
+1
