### ISSUE TITLE
Where can I find the chatui source code

### ISSUE THREAD

**Issue by xmwells** [letta-ai/letta#1353]
Could you please let me know if ChatUI is open source? Where can I find the source code?

**Comment by madgrizzle** [comment]
I asked about this on discord and though there appears to be a branch that contains an early version https://github.com/cpacker/MemGPT/tree/chatui-rebased-on-main, it hasn't been updated for months and is no longer the source of what you find here: https://github.com/cpacker/MemGPT/tree/main/memgpt/server/static_files
