### ISSUE TITLE
Support configuring multiple models at a time

### ISSUE THREAD

**Issue by lenaxia** [letta-ai/letta#1391]
**Is your feature request related to a problem? Please describe.**
When creating an agent, there is a drop down to select the LLM model to use for the agent, however currently there is no way to configure multiple models for MemGPT (at aleast from what I can find in the docs and has been told to me in Discord).

**Describe the solution you'd like**
Either/Or, multiple models should be configurable in the config file, if done manually then defining endpoints for each model would allow the user to utilize multiple serviecs at any given time.

Or, create discovery of models for a configured backend. e.g. LiteLLM Proxy or LocalAI both expose a `/models` endpoint which publishes all the models that are currently available. This would be populated into the drop down in "Create Agent". 

Especially in this case, but also in the first case, Agents should be flagged in the Agents List if their models are no longer available, and/or a default model could be configured as a fallback should a model become unavailable. 

**Describe alternatives you've considered**
No alternatives exist besides copying and pasting configs

**Comment by sarahwooders** [comment]
Should be supported with #1437
