### ISSUE TITLE
Adding/enabling new tools for existing agents

### ISSUE THREAD

**Issue by iamhitarth** [letta-ai/letta#1415]
**Is your feature request related to a problem? Please describe.**
I'm trying to use a MemGPT agent as an assistant for myself. In order to do that, I need to now start adding tools that can help it do different things such as read all the contents of a file (not just first 500 chars), delete a file etc.  I added the tool for reading all the contents of a text file (read_full_text_file) based on the [docs](https://memgpt.readme.io/docs/functions) but for some reason the agent is not able to use that tool and errors out with "Error: No function named read_full_text_file"

I even tried manually updating the `function_schemas` column associated with the preset that is associated with the agent in the Postgres DB but that didn't make a difference 😦 

**Describe the solution you'd like**
A simple way to provide existing agents access to new tools that get added.

**Comment by molander** [comment]
It used to be possible! Before we went all *cough* over-normalized db mad! ;)
Sarah, is it still possible manually? What if we edit the state, too?

Hitarth, horrible evil hack, but what I have done in a pinch is to take an existing function, conversation_search_date or something that doesn't get used much, and slam my function in there. Directly into /path/to/memgpt/memgpt/functions/function_sets/base.py. It ain't pretty and you need a smart LLM to roll with it but it does work-ish :D

**Comment by sarahwooders** [comment]
Yes should be possible if you edit the dictionary inside of `AgentState.state["functions"]` https://github.com/cpacker/MemGPT/blob/main/memgpt/agent.py#L1055
