### ISSUE TITLE
deployment with docker compose

### ISSUE THREAD

**Issue by wwjCMP** [letta-ai/letta#1430]
How do I set up my deployment with docker compose to use the ollama model and ollama Embed model

**Comment by sarahwooders** [comment]
We've only tested with OpenAI so far, so not sure if it'll work with Ollama (you can do `memgpt server` and that should work with Ollama though). We also are adding embedding support in #1384. 

It's a bit hacky right now, but the following *might* also work 
1. Install `pip install pymemgpt` 
2. Run `memgpt configure` and configure Ollama settings 
3. Run `docker compose up` and change this [line](https://github.com/cpacker/MemGPT/blob/main/compose.yaml#L38) to point to your file `~/.memgpt/config`

**Comment by chet-SA** [comment]
@wwjCMP  did it work for you? I had the same question and haven't had much luck yet but likely unrelated reasons.
