### ISSUE TITLE
Improving MemGPT Configuration 

### ISSUE THREAD

**Issue by sarahwooders** [letta-ai/letta#1437]
Currently, all MemGPT server configuration is contained in a config YAML file which is baked in the docker container. However, the container and configuration of the server should be separate. This is a proposal for how to change how MemGPT is configured to enable easier deployability. 

## Deployment Configuration 
Deployment configuration should all be done through environment variables to make it easy to provide at deployment time. 
**Note: we are not providing the LLM/embedding configurations at deployment time, so these will need to be provided by the administrator before users can start creating agents with the server**

Authentication 
* `MEMGPT_SERVER_PASS`: Administrator token to access to the server

By default, the server will store data locally (with sqlite + chroma). To use postgres, the following must be provided: 
* `MEMGPT_PG_URI`: Postgres URI (if specifies, uses Postgres as DB backend)

(Optional) Defaults configuration 
* `MEMGPT_DEFAULT_PERSONA`: Default persona 
* `MEMGPT_DEFAULT_HUMAN`: Default human 
* `MEMGPT_DEFAULT_PRESET`: Default preset  

(Optional) Archival storage configuration 
* `MEMGPT_ARCHIVAL_STORAGE_URI`: URI for archival storage DB (overrides) 
* `MEMGPT_ARCHIVAL_STORAGE_TYPE`: Must be `postgres`, `chroma`, `milvus`, or `qdrant`

(Optional) Recall/Metadata storage configuration 
* `MEMGPT_[RECALL/METADATA]_STORAGE_URI`: URI for DB (overrides) 
* `MEMGPT_[RECALL/METADATA]_STORAGE_TYPE`: Must be `postgres` or `sqlite`

## Secrets 
Secrets should also be passed in as environment variables. 
* `OPENAI_API_KEY` 
* `GROQ_API_KEY`
* `ANTHROPIC_API_KEY`

## Model Configuration 
LLM model and embedding model configuration need to be provided before the server can start running agents. These configurations can be updated on an existing server, or potentially even overriden by users. 

Adding the LLM and embedding model default can be done with: 
```
memgpt add llm-config -f <FILENAME> 
memgpt add embedding-config -f <FILENAME> 
```

The server administrator is responsible for adding model configurations to the server, once the server has been created. Once one or more configurations have been added, the administrator can set a default embedding/llm config for the server: 
```
memgpt set default-llm-config  -f <FILENAME>
memgpt set default-embedding-config  -f <FILENAME>  
```

LLM and embedding configurations will be stored in the `~/.memgpt` directory: 
```
~/.memgpt
    llm_model_configs/
        gpt-4.json
        llama-3.json
    embedding_model_configs/
        text-ada.json 
```

**Comment by norton120** [comment]
this might be a good opportunity to migrate to `pydantic_settings` across the codebase, it was set up as part of some earlier containerization work [here](https://github.com/cpacker/MemGPT/blob/main/memgpt/settings.py). Configs in the `Settings` class are set by matching envars - so `MEMGPT_SERVER_PASS` supplies the value for `settings.server_pass`. There are advantages to using a settings singleton as opposed to a config file - you can include dynamic code and default values all in one place, and it is an easy test hook. you can do 

```python
# conftest.py

@fixture
def override_db():
    try:
       old_pg_uri = settings.pg_uri
       settings.pg_uri = "postgresql+pg8000://memgpt:memgpt@localhost:5432/memgpt_test"
       yield # any calls to settings.pg_uri now have the test value
    finally:
       settings.pg_uri = old_pg_uri # put it back for good measure
```
ideally, centralize the configs, secrets and envars all to `settings.py` 

unless the goal is to allow some of the settings like storage_uri to be dynamically adjusted (like in a CMS) by the user - in that case we could put the defaults in `settings.py` and store the runtime configs in the db. Not sure if that fits though

**Comment by sarahwooders** [comment]
> this might be a good opportunity to migrate to `pydantic_settings` across the codebase, it was set up as part of some earlier containerization work [here](https://github.com/cpacker/MemGPT/blob/main/memgpt/settings.py). Configs in the `Settings` class are set by matching envars - so `MEMGPT_SERVER_PASS` supplies the value for `settings.server_pass`. There are advantages to using a settings singleton as opposed to a config file - you can include dynamic code and default values all in one place, and it is an easy test hook. you can do
> 
> ```python
> # conftest.py
> 
> @fixture
> def override_db():
>     try:
>        old_pg_uri = settings.pg_uri
>        settings.pg_uri = "postgresql+pg8000://memgpt:memgpt@localhost:5432/memgpt_test"
>        yield # any calls to settings.pg_uri now have the test value
>     finally:
>        settings.pg_uri = old_pg_uri # put it back for good measure
> ```
> 
> ideally, centralize the configs, secrets and envars all to `settings.py`
> 
> unless the goal is to allow some of the settings like storage_uri to be dynamically adjusted (like in a CMS) by the user - in that case we could put the defaults in `settings.py` and store the runtime configs in the db. Not sure if that fits though

Yeah I think this is the way to go. The storage configuration shouldn't be dynamically configurable, although the LLM/embedding model configurations should be.

**Comment by 99bits** [comment]
### Using MemGPT as a master agent to coordinate specialized LLM agents

We're developing an online course system and want to use MemGPT as the master agent to coordinate specialized agents for different subjects. Each specialized agent would use the LLM best suited for its topic. For example:

- Master agent (MemGPT): OpenAI
- Math agent: Google's Gemini
- Writing agent: Anthropic's Claude

Is it possible to configure MemGPT to manage these diverse LLM agents? How would we implement this multi-model approach within the MemGPT framework?

**Comment by rishavhada** [comment]
@sarahwooders is it now possible to configure multiple models at a time? not sure how to go about it.
