### ISSUE TITLE
a bug? AttributeError: module 'memgpt' has no attribute '__version__'

### ISSUE THREAD

**Issue by maxadc** [letta-ai/letta#1439]
![Image](https://github.com/cpacker/MemGPT/assets/23376041/d135f14d-459a-4471-808a-3472f77e60a9)

![Image](https://github.com/cpacker/MemGPT/assets/23376041/7d6a4a94-294b-4350-a71b-a67d99c1c1b5)

**Comment by sarahwooders** [comment]
What version of MemGPT are you using? Can you do `pip install -U pymemgpt`?

**Comment by Guard1an** [comment]
This happened to me when I incidentally installed a wrong package with
pip install memgpt 
Instead of
pymemgpt

**Comment by dojian** [comment]
I solved it by go to file /python3.9/site-packages/memgpt/__init__.py and added: __version__ = "0.1.0"  # or any version number you prefer
