### ISSUE TITLE
Link agents to attached data instead of copying it to archival memory

### ISSUE THREAD

**Issue by theocnrds** [letta-ai/letta#1440]
**Is your feature request related to a problem? Please describe.**
When I attach a data source to an agent all passages of this source are copied over to the agent's archival memory. This is not only slow as already stated in #371 but also blows up my database over time when attaching the same data source to a large number of agents.

**Describe the solution you'd like**
The agent should be allowed to search both archival memory and passages that are attached to it.

**Describe alternatives you've considered**
Only workaround would be storing data outside dedicated memgpt stores, adding logic that checks whether an agent is allowed to access a specific source and modifying the search_archival_memory function. That would require a fork obviously.

**Comment by sarahwooders** [comment]
Yes we did this as a hack to allow for easy connections to external data sources - we would eventually like to move to instead querying across multiple tables. 

A possible workaround is to add a tool call that queries the data source: https://memgpt.readme.io/docs/functions
