### ISSUE TITLE
Explicit Python Version Support in CI

### ISSUE THREAD

**Issue by norton120** [letta-ai/letta#1458]
**Is your feature request related to a problem? Please describe.**
On the path to enterprise-grade software, we should be testing against any Python version we want to support.

**Describe the solution you'd like**
The old-school solution would be to use a map in tox and run tests on every formally released patch via venvs. Today it's probably better done via docker images for each version - better isolation and the Github CI ecosystem likes containers. 

For local dev typically minors are good enough (otherwise even in parallel the testing will take forever)

development should be possible in any supported Python version - because it is supported 😉 

**Describe alternatives you've considered**
- Only supporting latest 😞 
- create a tox version pipeline - totally fine to do, but docker is already an important part of the MemGPT ecosystem so less technologies == better

**Additional context**
This will be part of a larger CI refinement to ensure stable builds across supported versions

**Comment by sarahwooders** [comment]
I believe we only need to do this for the client functionality and CLI, since otherwise the default way to interact with MemGPT is via a service which can be more limited in Python version support.
