### ISSUE TITLE
Mistral API broken

### ISSUE THREAD

**Issue by cpacker** [letta-ai/letta#1478]
https://discord.com/channels/1161736243340640419/1161736244074659893/1254889719456596082

```
the first error I get is 
mistralai.exceptions.MistralAPIException: Status: 400. Message: {"object":"error","message":"Unexpected role 'user' after role 'tool'","type":"invalid_request_error","param":null,"code":null}
```

**Comment by sarahwooders** [comment]
For this issue, how was the user passing in the Mistral API key? We don't have an integration with mistral

**Comment by Sapessii** [comment]
hi! I was using the openai preset

**Comment by DavidBellamy** [comment]
Any headway with this @cpacker ? I'm having the same issue.

**Comment by Sapessii** [comment]
hi @cpacker and @sarahwooders , do you have any update on this? thank you

**Comment by sarahwooders** [comment]
We support Mistral through [Together AI](https://docs.letta.com/models/together) support - would that work for you @Sapessii ?

**Comment by mattzh72** [comment]
To add more context here, Mistral, Cohere, and some other providers expect a specific sequence of messages:

1. User Message: Initiates the interaction with a query or command.
2. Assistant's Thought: The assistant articulates its reasoning process.
3. Tool Call: The assistant invokes a tool to perform a specific action.
4. Tool Response: The tool returns the result of the action.
5. Assistant's Conclusion: The assistant provides the final response based on the tool's output.

Adhering to this structured sequence is crucial for the API to function correctly. This design aligns with the ReACT framework, which emphasizes a clear alternation between reasoning and action steps. However, this doesn't interoperate well with Letta, which has much more flexibility (e.g. multi-turn function calling). 

Can I ask why you're interested in using Mistral over other providers?
