### ISSUE TITLE
Unable to use Anyscale models

### ISSUE THREAD

**Issue by BaLaurent** [letta-ai/letta#1490]
**Describe the bug**
 i'm facing an issue with memgpt when trying to run it using anyscale it tell me that it's not using the proper method (it's trying to use input_value='text_completion' instead of input_value='text_chat.completion' 
The issue happen when trying to use anyscale as a provider for an openai compatible endpoint

**Please describe your setup**
- [ ] How did you install memgpt?
  - `pip install pymemgpt`
- [ ] Describe your setup
  - Windows 11
  - cmd.exe

**Screenshots**
![image](https://github.com/cpacker/MemGPT/assets/27644308/21ea75d4-be48-4850-a05c-a5f3c3f4c063)

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.

```
[defaults]
preset = memgpt_chat
persona = sofia
human = Laurent

[model]
model = meta-llama/Meta-Llama-3-70B-Instruct
model_endpoint = https://api.endpoints.anyscale.com/v1
model_endpoint_type = openai
context_window = 8192

[embedding]
embedding_endpoint_type = hugging-face
embedding_endpoint = https://embeddings.memgpt.ai
embedding_model = BAAI/bge-large-en-v1.5
embedding_dim = 1024
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = C:\Users\Octop\.memgpt\chroma

[recall_storage]
type = sqlite
path = C:\Users\Octop\.memgpt

[metadata_storage]
type = sqlite
path = C:\Users\Octop\.memgpt

[version]
memgpt_version = 0.3.17

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000
```

**Comment by sarahwooders** [comment]
I also heard that Anyscale is deprecating their LLM endpoints, so you might want to try try a different provider? Sometimes there are issues with tool calling even for OpenAI-compliant inference endpoints since everyone does tool calling differently.
