### ISSUE TITLE
TypeError: 'staticmethod' object is not callable

### ISSUE THREAD

**Issue by tyler-suard-parker** [letta-ai/letta#1496]
**Describe the bug**
Trying to run the autogen memgpt demo, using Python 3.11.9
\.venv\lib\site-packages\memgpt\server\server.py", line 115, in LockingServer
    def user_message(self, user_id: str, agent_id: str, message: str) -> None:
TypeError: 'staticmethod' object is not callable

**Please describe your setup**
- [X ] How did you install memgpt?
pip install pymemgpy
- [x ] Describe your setup
windows 11, using a python script
**Screenshots**

**Additional context**
I am just trying to run the autogen with memgpt tutorial in your documentation here: https://memgpt.readme.io/docs/autogen

**Comment by cqhblg** [comment]
I have same problem，when will solve？

**Comment by tyler-suard-parker** [comment]
@cpacker I can't use MemGPT because of this issue.  I was hoping to add memory to my agents.  I like your paper and your idea, but right now your code is unusable for me.

**Comment by majiayun** [comment]
I have same error (Python 3.12.4)

**Comment by tyler-suard-parker** [comment]
@cpacker I got the same error with Python 3.12.  Understand you and Vivian are busy with your studies.  It might be an idea to offer this repo to the Linux foundation.  They currently maintain PyTorch, so they may be interested in your LLM-as-OS idea.

**Comment by Nada17-21** [comment]
I tried using Python3.10 on ubuntu22.04 and I didn't get this problem.
