### ISSUE TITLE
Add a `client.get_source(name=source_name)` function to client to retrieve `source.id` 

### ISSUE THREAD

**Issue by tiro2000** [letta-ai/letta#1520]
**Is your feature request related to a problem? Please describe.**
I am trying to attach Source to an Agent programmatically using the example code provided, but the example at https://memgpt.readme.io/docs using source_name , when I try that I get an error, it should be the source_id

**Describe the solution you'd like**
providing access to source.id using functions like get("soruce_name")  or such function that would return source_id, so that can be used to attach the source to the Agent inside the code, weather it's created using CLI or initially during the setup of sources then I need to access it later in my code.

**Describe alternatives you've considered**
using CLI to create the source but I can just get the ID all resources using get REST API and not just specific source, I want to do that using the client.
**Additional context**
 ## How to Get Access to myBook.id ?? ( assuming I created it using CLI or I created it insitally then want to use it later , current 
    example using source_name which is not the right parameter ##

      job = client.load_file_into_source(filename=file_path, source_id=mybook_source.id)
     client.attach_source_to_agent(source_id=memgpt_source.id, agent_id=agent_id=custom_agent.id)

**Comment by sarahwooders** [comment]
When you create a source, you get a `SourceModel` object back and can grab the `id` field. We should also add a `client.get_source(name=source_name)` to get the object/ID back though...

**Comment by tiro2000** [comment]
@sarahwooders Thanks for your prompt response, Yes the thing is I wanted to access the Id later not just next to creating the source using client.create_source , even assuning its created using CLI or UI not just client , so that it can be used later to upload document or even be deleted or accessed.
I was thinking of something like the below code,  ( just thinking )
def get_source_id_by_name(client, source_name):
    sources = client.list_sources().sources
    for source in sources:
        if source.name == source_name:
            return source.id
    return None
