### ISSUE TITLE
Agents not showing in Dev Portal ( UI )

### ISSUE THREAD

**Issue by tiro2000** [letta-ai/letta#1522]
**Describe the bug**
Agent already created using Client Code , given Id and other details like default ( that's happening even with Basic Agent ) and its showing in the backend ( sql lite, showing in the Agents table with all fields ( agent_id, user_id, name, persona , human, preset, llm config ( {"model": "gpt-4o", "model_endpoint_type": "openai", "model_endpoint": "https://api.openai.com/v1", "model_wrapper": null, "context_window": 8192} ) , 
- embeddings_config ( {"embedding_endpoint_type": "hugging-face", "embedding_endpoint": "https://embeddings.memgpt.ai", 
"embedding_model": "BAAI/bge-large-en-v1.5", "embedding_dim": 1024, "embedding_chunk_size": 300} ) . 

Yet in the UI dev portal its not showing some of those created agents.

**Please describe your setup**
- [ ] How did you install memgpt?
  git clone, then using docker build file, then started memgpt server , then I use the password created as in the client example to create Agents
- [ ] Describe your setup
  - Windows
  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal)
  - PowerShell Terminal From Windows ( using another Powershell Terminal from Visual source code to access the Server using client example )

**Screenshots**

**Additional context**
def main(): 
    # Create an admin client
    token = "3Uz8TeKj4OY-qdZAWi3R5A"  # Server Token
    admin = Admin(base_url="http://localhost:8283", token=token)

    client = create_client(base_url="http://localhost:8283", token='3Uz8TeKj4OY-qdZAWi3R5A')
    
    basic_agent = client.create_agent(
        name="basic_agent", 
    )

    print(f"Created agent: {basic_agent.name} with ID {str(basic_agent.id)}")

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = gpt-4
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
context_window = 8192

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_model = text-embedding-ada-002
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = C:\Users\king_\.memgpt\chroma

[recall_storage]
type = sqlite
path = C:\Users\king_\.memgpt

[metadata_storage]
type = sqlite
path = C:\Users\king_\.memgpt

[version]
memgpt_version = 0.3.15

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by sarahwooders** [comment]
When you're viewing the dev portal, are you entering the admin password or the user token ("3Uz8TeKj4OY-qdZAWi3R5A")? If you want to see agents created by the user, you should enter the user token as the dev portal password (make sure you log out first). If you log in with the admin password, you'll only see agents created with the default UUID corresponding to the admin. Sorry this isn't clear in the docs!

**Comment by tiro2000** [comment]
@sarahwooders Thanks for your response, Yes I am entering the Admin password,
 I assumed the Admin should be able to view all Agents whereas the user is the one who can just see those created by him
 I am also assuming if I use user Token Key created by Admin to  create Client , then using the client to create Agent , so that Agent should belong to that client , also assuming when I create using Admin pass that would be a default user assigned to client ( almost 000000000000 ) if that's what's happening or not , please verify ? )

**Comment by cpacker** [comment]
Hi @tiro2000 - actually right now the dev portal will only show agents created by the admin user (we haven't really optimized the dev portal UI for an "admin" experience yet).

I'm adding this to the TODOs for the dev portal, thank you for bringing this up.
