### ISSUE TITLE
No reply when MemGPT decides to update archival_memory

### ISSUE THREAD

**Issue by yuleisheng** [letta-ai/letta#1524]
**Describe the bug**
When I chat with MemGPT agents, if the agent decides to add my message to archival_memory, it only outputs the function response, there are no other replies other than function response. 

**Please describe your setup**
- use Dev Portal to chat

**Screenshots**
<img width="485" alt="Screenshot 2024-07-08 at 9 21 15 AM" src="https://github.com/cpacker/MemGPT/assets/11828090/e56f6805-8900-4b2e-b68d-dbc0a8db8c55">

**Additional context**

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.

**Comment by sarahwooders** [comment]
what model are you using?

**Comment by yuleisheng** [comment]
gpt-4o

**Comment by sarahwooders** [comment]
ah ok - unfortunately gpt-4o and gpt-3.5 are both very bad at function calling and multi-step reasoning, so don't work well with MemGPT. For prototyping, I'd recommend gpt-4, and if you need to optimize cost @cpacker can help with finding a good open model to use.

**Comment by yuleisheng** [comment]
Sarah, really appreciate you replying to my question on Sunday night!
I will try gpt-4 for prototyping.
In my case, I think function calling is correct, it's just that there's no reply to user, i think it could be solved by prompting?
