### ISSUE TITLE
[Bug/Feature] Outdated documentation for CLI and presets

### ISSUE THREAD

**Issue by robonxt-ai** [letta-ai/letta#1552]
**Is your feature request related to a problem? Please describe.**
The documentation seems to be outdated, or partially working as of v0.3.19: 
1. Presets are not removed from the docs or at least mentioned as no longer supported
2. `memgpt delete [human/persona] --name [NAME]` in the [Concepts page](https://memgpt.readme.io/docs/concepts) is not valid. What works is `memgpt delete [human/persona] [NAME]` (no need for the `--name` when deleting.)

**Describe the solution you'd like**
Update the documentation.

**Additional context**
Is the documentation on the memgpt.ai website being auto updated? I'm also not seeing where the concepts md file is in the github.

**Comment by sarahwooders** [comment]
Yes sorry we made a bunch of changes recently, so the documentation is out of date.
