### ISSUE TITLE
Back again after months away: Still can't make use of text files for humans, personas or agents

### ISSUE THREAD

**Issue by philiprhoades** [letta-ai/letta#1558]
**Describe the bug**

Trying to get memgpt to make use of text files either results in python errors, the files being imported into DBs being ignored or the info in the text files just being ignored and not even making it the DBs.

**Please describe your setup**
- [ ] How did you install memgpt?

pip install -U pymemgpt

- [ ] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?

Fedora 40 Podman container but with python 3.11

  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal)

memgpt run # to get a .config with defaults - then trying these sorts of things:

memgpt run --human phr
memgpt run --agent phirho
memgpt run --persona phirho
memgpt run --persona phirho --human phr
memgpt run --agent phirho --persona phi_rho --human phr

memgpt add . . etc gives python errors . .

I think there are too many problems to be resolved by back and forth on GH - if someone thinks I am just clueless and stuffing up, I am happy to provide a login via ZeroTier for them to show me what I am doing wrong - also happy to pay for their time if they are successful . . I REALLY need to be able to actually start using MemGPT - at least for my family and close friends (otherwise known as alpha-testers . .).

Thanks,
Phil.

**Comment by starsnatched** [comment]
I am unable to reproduce the bug, have you tried to use human/persona from raw text file (without .txt)?
Try creating a raw text file in vscode named phr, and run `memgpt add human -f phr --name phr` then run `memgpt run --human phr`.

**Comment by philiprhoades** [comment]
Hmm interesting - phr.txt IS raw text (produced with Vim) - are you saying that it is only the ".txt" extension that matters?  I will give that a go without the extension anyway.

Thanks.

**Comment by philiprhoades** [comment]
As before, a new Podman container created as above, then:

- pip install -U pymemgpt
- values changed for: 
CORE_MEMORY_PERSONA_CHAR_LIMIT = 16384
CORE_MEMORY_HUMAN_CHAR_LIMIT = 16384
in /usr/local/lib/python3.12/site-packages/memgpt/constants.py
- Created config file using defaults with:
memgpt run
- typed initial message, received response and then exited
- put plain text file "phr" (8501 bytes) in humans dir
- used:
memgpt run --human phr

Got:
```
An exception occurred when running agent.step(): 
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/memgpt/main.py", line 415, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/memgpt/main.py", line 384, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning, tokens_accumulated = memgpt_agent.step(
                                                                                          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/memgpt/agent.py", line 722, in step
    raise e
  File "/usr/local/lib/python3.12/site-packages/memgpt/agent.py", line 643, in step
    raise Exception(f"Hit first message retry limit ({first_message_retry_limit})")
Exception: Hit first message retry limit (10)
? Retry agent.step()? No

> Enter your message: /exit
```

**Comment by sarahwooders** [comment]
I'd recommend using the developer portal (described in the README) or the Python client -- we made some changes recently that broke the CLI, but will add a PR to fix these.

**Comment by sarahwooders** [comment]
I think there may actually be issues with `memgpt run` with the agent/human flag, so re-opening. 

Also, if you need help with general setup please DM us on discord!
