### ISSUE TITLE
Add GraphRAG support

### ISSUE THREAD

**Issue by distributev** [letta-ai/letta#1561]
https://www.microsoft.com/en-us/research/project/graphrag/

GraphRAG (Graphs + Retrieval Augmented Generation) is a technique for richly understanding text datasets by combining text extraction, network analysis, and LLM prompting and summarization into a single end-to-end system.

https://www.youtube.com/watch?v=LDh5MdR-CPQ
**LlamaIndex Webinar: Advanced RAG with Knowledge Graphs (with Tomaz from Neo4j)**

https://www.youtube.com/watch?v=Q7E97TSmGyI
**Neo4j Live: Personal Knowledge Vault with Neo4j GraphRAG**

**Comment by sarahwooders** [comment]
Yes this would be great to have - it should be possible to implement by creating an agent with a custom set of tools https://memgpt.readme.io/docs/adding-custom-tools-to-memgpt#overriding-default-tools

**Comment by distributev** [comment]
Maybe the current microsoft graphrag implementation can be "wrapped" as tools.

or maybe just a light integration similar with how autogen integration is implemented

https://github.com/microsoft/graphrag

https://github.com/Azure-Samples/graphrag-accelerator
