### ISSUE TITLE
MemoryModule validation errors on agents stored in database

### ISSUE THREAD

**Issue by cpacker** [letta-ai/letta#1567]
Via discord: https://discord.com/channels/1161736243340640419/1161736244074659893/1265168228699738144

When the agent somehow already saved a larger than allowed size, it will fail to get agents on portal since it wants to load and cache every one that exists:

```MemGPT.memgpt.server.server - ERROR - Error occurred while trying to get agent 5a6dac48-b0b0-4720-bf3d-0e50f6f1e3b4:
1 validation error for MemoryModule
value
  Value error, Edit failed: Exceeds 2000 character limit (requested 2187). [type=value_error, input_value="An adventurer in skyrim....dge if i stare too long", input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
Traceback (most recent call last):
  File "C:\Projects\MemGPT\memgpt\server\server.py", line 348, in _load_agent
    memgpt_agent = Agent(agent_state=agent_state, interface=interface, tools=tool_objs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\MemGPT\memgpt\agent.py", line 165, in __init__
    self.memory = BaseMemory.load(self.agent_state.state["memory"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\MemGPT\memgpt\memory.py", line 78, in load
    obj.memory[key] = MemoryModule(**value)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\johnf\AppData\Local\pypoetry\Cache\virtualenvs\pymemgpt-zmpdwjkq-py3.12\Lib\site-packages\pydantic\main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for MemoryModule
value
  Value error, Edit failed: Exceeds 2000 character limit (requested 2187). [type=value_error, input_value="An adventurer in skyrim....dge if i stare too long", input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
2024-07-22 05:27:20,171 - MemGPT.memgpt.server.server - INFO - Grabbing agent user_id=00000000-0000-0000-0000-000000000000 agent_id=5a6dac48-b0b0-4720-bf3d-0e50f6f1e3b4 from database
2024-07-22 05:27:20,171 - MemGPT.memgpt.server.server - INFO - Creating an agent object
2024-07-22 05:27:20,179 - MemGPT.memgpt.server.server - ERROR - Error occurred while trying to get agent 5a6dac48-b0b0-4720-bf3d-0e50f6f1e3b4:
1 validation error for MemoryModule
```

**Describe the bug**

@sarahwooders a few things going wrong here:
1. somehow agents are getting memories edited to have larger than the max stated limit
2. when this agent gets init-ed, it causes a runtime error
3. all agents are getting loaded because of the way the frontend requests (will be fixed on #1525)

Reasonable TODOs:
- Adds tests for what happens with ChatMemory when we: (1) overflow via `replace`, (2) overflow via `append`
  - Goal is to make sure we aren't allowing overflow
- Make sure we don't hard error on validation errors, instead we just truncate
  - In the server log it looks like there's a runtime error, this should be a warning instead

**Comment by orkatoons** [comment]
Hi, were you able to solve this yet by any chnage?

**Comment by Nostoi** [comment]
It seems that the same thing is true when launching the CLI when a portion of the memory is over the limit: 

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for MemoryModule
value
  Value error, Edit failed: Exceeds 5000 character limit (requested 6183). [type=value_error, input_value=["{'task_id': 'd1c271da-4...ow_up_interval': None}"], input_type=list]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
    ```

**Comment by yxt0531** [comment]
It happened to me as well unfortunately, it worked for a few days just fine, then I got the same error next time I tried to start memgpt.`  Value error, Edit failed: Exceeds 2000 character limit (requested 2245). [type=value_error, input_value="Nono Kros: Male, born Oc...ive engines like Godot.", input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error`

**Comment by sarahwooders** [comment]
I think a solution for this if you already have existing agents with large persona/human fields, is to increase the limit of the core memory with `memgpt run --core_memory_limit 5000`
