### ISSUE TITLE
Can't edit data source

### ISSUE THREAD

**Issue by FellowTraveler** [letta-ai/letta#1588]
**Describe the bug**
<img width="697" alt="image" src="https://github.com/user-attachments/assets/72a70814-bf3d-4290-93df-418cf2f60d9c">

^^^^^ NOTICE the error message in the lower right of the image.

Trying to change (EDIT) a data source, acts like there's a failure CREATING it. See above error message. This shows up in the log each time you click "edit" (which should be "save" button):

```
INFO:     ::1:59448 - "POST /api/sources/bd63a217-f153-41b0-a9f4-0d66ca29fe26 HTTP/1.1" 405 Method Not Allowed
INFO:     ::1:59448 - "POST /api/sources/bd63a217-f153-41b0-a9f4-0d66ca29fe26 HTTP/1.1" 405 Method Not Allowed
INFO:     ::1:59457 - "POST /api/sources/bd63a217-f153-41b0-a9f4-0d66ca29fe26 HTTP/1.1" 405 Method Not Allowed
```

**Please describe your setup**
- [ ] How did you install memgpt?
  - `pip install pymemgpt`? `pip install pymemgpt-nightly`? `git clone`?

git clone, pip install -e .

- [ ] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?
  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal)

MacOS Silicon Sonoma 14.3
I'm running memgpt from the terminal in its own Conda environment.

**Screenshots**

**Additional context**

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.

[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = gpt-4o-mini-2024-07-18
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
context_window = 128000

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_model = text-embedding-ada-002
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /Users/au/.memgpt/chroma

[recall_storage]
type = sqlite
path = /Users/au/.memgpt

[metadata_storage]
type = sqlite
path = /Users/au/.memgpt

[version]
memgpt_version = 0.3.21

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by sarahwooders** [comment]
Thanks for reporting this! Are you able to create data sources via the CLI? We'll try to get a fix out for this soon.

**Comment by jward92** [comment]
@sarahwooders hope it's ok but I took a shot at fixing this: https://github.com/cpacker/MemGPT/pull/1599
