### ISSUE TITLE
Autogen create_memgpt_autogen_agent_from_config - ImportError: cannot import name 'add_default_presets' from 'memgpt.presets.presets' 

### ISSUE THREAD

**Issue by ibabbar** [letta-ai/letta#1589]
**Describe the bug**
I cannot use basic examples when trying to use autogen agent: `create_memgpt_autogen_agent_from_config`

**Please describe your setup**
- [ ] How did you install memgpt?
  - `pip install pymemgpt`? `pip install pymemgpt-nightly`? `git clone`?
  - pip install pymemgpt
- [ ] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?
  - MacOS
  - How are you running `memgpt`?
  - Python 3.10 SDK

**Screenshots**
<img width="648" alt="image" src="https://github.com/user-attachments/assets/f9c881ee-b732-4b21-8519-d4acb2741100">

**Additional context**

**MemGPT Config**

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by mctouch** [comment]
Please describe your setup

 How did you install memgpt?
pip install pymemgpt? pip install pymemgpt-nightly? git clone?
pip install pymemgpt
 Describe your setup
What's your OS (Windows/MacOS/Linux)?
MacOS
How are you running memgpt?
Python 3.12.4

same issue 

ll /Users/mctouch/micromamba/envs/autogen/lib/python3.12/site-packages/memgpt/presets/presets.py
-rw-r--r--@ 1 mctouch  staff   3.4K 29 Jul 20:27 /Users/mctouch/micromamba/envs/autogen/lib/python3.12/site-packages/memgpt/presets/presets.py
❯ /Users/mctouch/micromamba/envs/autogen/bin/python /Users/mctouch/code/MemGPT/memgpt/autogen/examples/agent_groupchat.py
Traceback (most recent call last):
  File "/Users/mctouch/code/MemGPT/memgpt/autogen/examples/agent_groupchat.py", line 168, in <module>
    coder = create_memgpt_autogen_agent_from_config(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mctouch/micromamba/envs/autogen/lib/python3.12/site-packages/memgpt/autogen/memgpt_agent.py", line 465, in create_memgpt_autogen_agent_from_config
    autogen_memgpt_agent = create_autogen_memgpt_agent(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mctouch/micromamba/envs/autogen/lib/python3.12/site-packages/memgpt/autogen/memgpt_agent.py", line 348, in create_autogen_memgpt_agent
    from memgpt.presets.presets import add_default_presets
ImportError: cannot import name 'add_default_presets' from 'memgpt.presets.presets' (/Users/mctouch/micromamba/envs/autogen/lib/python3.12/site-packages/memgpt/presets/presets.py). Did you mean: 'add_default_tools'?

❯ ll /Users/mctouch/micromamba/envs/autogen/lib/python3.12/site-packages/memgpt/presets/presets.py
-rw-r--r--@ 1 mctouch  staff   3.4K 29 Jul 20:27 /Users/mctouch/micromamba/envs/autogen/lib/python3.12/site-packages/memgpt/presets/presets.py


cat /Users/mctouch/micromamba/envs/autogen/lib/python3.12/site-packages/memgpt/presets/presets.py | grep add_default_presets

No references found in the repo.

Mac osx

**Comment by sarahwooders** [comment]
Sorry the autogen integration is broken right now. If you are trying to do multi-agent, we recommend just passing messages between agents (examples coming soon).

**Comment by raolak** [comment]
@sarahwooders blocked on same issue...wanted to try memgpt with autogen. any idea on when we can expect fix?

**Comment by ibabbar** [comment]
@sarahwooders even for single ConversableAgents - I'd love examples, and even happy to recommend/contribute fixes if you need assistance

**Comment by CellCS** [comment]
Reproduce this issue by using 'azure' in `https://github.com/cpacker/MemGPT/blob/main/memgpt/autogen/examples/agent_groupchat.py`

![image](https://github.com/user-attachments/assets/6aeaec93-3ec9-48c4-9656-40695da33bcf)


![image](https://github.com/user-attachments/assets/a4c77712-a66c-4a3d-94b8-f8411282349a)

**Comment by Harinisri29** [comment]
Hi I am also facing the same issue. Did anyone found the solution?

ImportError: cannot import name 'add_default_presets' from 'memgpt.presets.presets'

**Comment by mustangproject** [comment]
See the same issue.  Any fix yet?  
ImportError: cannot import name 'add_default_presets' from 'memgpt.presets.presets' (/home/vor/Documents/VOR_PROJECTS/VOR_PYTHON/env-vor/lib/python3.11/site-packages/memgpt/presets/presets.py)

**Comment by milorddev** [comment]
same issue on ubuntu 22.04 using ollama local setup, might to some digging myself, I'll update here if I find something
