### ISSUE TITLE
feat: add endpoint to delete agent

### ISSUE THREAD

**Issue by goetzrobin** [letta-ai/letta#1649]
**Is your feature request related to a problem? Please describe.**

Currently, the REST API does not expose an endpoint to delete an agent

**Describe the solution you'd like**

Implement the DELETE endpoint for `/agents/{agentId}` that deletes an agent

**Describe alternatives you've considered**

**Additional context**

**Comment by 4shub** [comment]
I think you are looking for this:
https://github.com/cpacker/MemGPT/blob/e3c80dee8e227db84274a76a2df47a2ce010f04c/memgpt/server/rest_api/agents/config.py#L139
