### ISSUE TITLE
OpenRouter API support

### ISSUE THREAD

**Issue by strueman** [letta-ai/letta#1670]
Allow using OpenRouter models via the openai compatible API, allows access to Anthropic, Openai, Meta and other providers of open source and proprietary models through a single source, with a single point of payment and a single API key.

The api endpoint: https://openrouter.ai/api/v1 
A json formatted list of models can be fetched via API if usefull: https://openrouter.ai/api/v1/models

Full Docs: https://openrouter.ai/docs/

I had a look at doing this myself, but without more familiarity with memgpt I cant figure it out all the places needed to be updated. It seems that endpoint providers and model config is widely spread throughout everything.

**Comment by hilmishah** [comment]
Can this be revisited again? I prefer to use openrouter as it provides more models including free

**Comment by quantumalchemy** [comment]
yeah! would be great to use openrouter.ai  with model_endpoint_type="openai"
In theory should work with  as it uses openai endpoint -->
---
agent = client.agents.create(
name="thedude", 
#memory_blocks=[],
llm_config=LlmConfig(
	model="qwen/qwq-32b:free",
	model_endpoint_type="openai",
	model_endpoint="https://openrouter.ai/api/v1",
	api_key=os.getenv("OPENAI_API_KEY"),
	context_window=16384,
),
embedding_config=EmbeddingConfig(embedding_endpoint_type='hugging-face', embedding_endpoint='https://embeddings.memgpt.ai', embedding_model='letta-free', embedding_dim=1024, embedding_chunk_size=300),
)

BUT:
Lots of ERRORS:

 "OPTIONS /v1/agents/agent-9abc78bf-d482-440b-9e0c-4d4a64738198/context HTTP/1.1" 200 OK
/app/letta/agent.py:111: UserWarning: Tool rules only work reliably for the latest OpenAI models that support structured outputs.
..
Letta.letta.server.rest_api.routers.v1.tools - WARNING - No API keys found for Composio. Defaulting to the environment variable...
httpx - INFO - HTTP Request: POST https://openrouter.ai/api/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
Letta.letta.llm_api.openai - ERROR - Parsing ChatCompletion stream failed with error:
Internal Server Error
...
Letta.letta.agent - ERROR - step() failed with an unrecognized exception: 'Internal Server Error'
...
openai.InternalServerError: Internal Server Error
/app/letta/server/rest_api/utils.py:133: UserWarning: SSE stream generator failed: Internal Server Error
  warnings.warn(f"SSE stream generator failed: {e}")
Letta.letta.server.rest_api.utils - ERROR - Caught unexpected Exception: Internal Server Error

On and on
