### ISSUE TITLE
Tools - Documentation update

### ISSUE THREAD

**Issue by raolak** [letta-ai/letta#1709]
**Describe the bug**
Seems like we don't need to pass self:Agent while creating the tool. Earlier I ingested the tool using the api...but same api now fails...After removing the  Agent as argument for the function, it worked...

Can you please confirm what is the semantic to create new tool? May be it requires documentation update.

Thanks

**Comment by mahiro72** [comment]
Hello @raolak  , I'm interested in working on this issue. Would it be okay for me to pick it up?

**Comment by raolak** [comment]
Hi @mahiro Thank you ! I can collaborate.  I need to double check on what
has changed, we can update the doc only after testing and getting that
reviewed with memgpt team. But we can work together. We can have a quick
chat !

Thank you !
