### ISSUE TITLE
OpenAI Base URL needed

### ISSUE THREAD

**Issue by mr-good-bye** [letta-ai/letta#1760]
** Need an OpenAI Base URL in .env **

Hi There!

I am requesting support of additional .env parameters:
1. OPENAI_BASE_URL - for proxies and custom openai
2. OPENAI_DEFAULT_MODEL - for selecting other models e.g. gpt-4o

**Comment by pinpolhoxx** [comment]
download
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Archive password: changeme
I put the necessary dlls in the archive
