### ISSUE TITLE
Problem in conversation_search_date

### ISSUE THREAD

**Issue by peruginia** [letta-ai/letta#1890]
**Describe the bug**
When the server search in memory 

conversation_search_date({
"start_date": "2024-10-14",
"end_date": "now",
"request_heartbeat": true
})

i receive the error (bad interpretation of now ?)

{
"status": "Failed",
"message": "Error calling function conversation_search_date: invalid literal for int() with base 10: 'now'",
"time": "2024-10-15 07:30:32 AM UTC+0000"
}

**Please describe your setup**
-  i use git clone (updatedt now 15/10/2024) and i start sudo docker compose up

- Ubuntu linux, letta starting with docker

**Additional context**
LLM is local with ollama, 

LETTA_LLM_MODEL=starsnatched/memgpt:nemo
LETTA_LLM_CONTEXT_WINDOW=32000

## Embeddings
LETTA_EMBEDDING_ENDPOINT_TYPE=ollama
LETTA_EMBEDDING_MODEL=mxbai-embed-large
LETTA_EMBEDDING_DIM=512

Until the git update it seem to work correctly

![image](https://github.com/user-attachments/assets/cf1e49ff-f826-4edf-b250-6417889929be)

**Comment by sarahwooders** [comment]
Thanks for posting this issue, we will have a fix soon!
