### ISSUE TITLE
Unexpected Application Error! Cannot assign to read only property '0' of string 'python ./plex_debrid/main.py'

### ISSUE THREAD

**Issue by netixc** [letta-ai/letta#1905]
**Describe the bug**
```
TypeError: Cannot assign to read only property '0' of string 'python ./plex_debrid/main.py'
    at code (http://192.168.51.245:8083/assets/index-dc228d4a.js:204:14984)
    at RC (http://192.168.51.245:8083/assets/index-dc228d4a.js:38:19538)
    at AF (http://192.168.51.245:8083/assets/index-dc228d4a.js:40:44055)
    at kF (http://192.168.51.245:8083/assets/index-dc228d4a.js:40:39787)
    at pV (http://192.168.51.245:8083/assets/index-dc228d4a.js:40:39715)
    at wg (http://192.168.51.245:8083/assets/index-dc228d4a.js:40:39568)
    at y1 (http://192.168.51.245:8083/assets/index-dc228d4a.js:40:35933)
    at cR (http://192.168.51.245:8083/assets/index-dc228d4a.js:40:36737)
    at Oi (http://192.168.51.245:8083/assets/index-dc228d4a.js:38:3279)
    at http://192.168.51.245:8083/assets/index-dc228d4a.js:40:34263
```

**Please describe your setup**
- [x] How did you install letta?
  - git clone memgpt , docker compose up
- [x] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?
  - How are you running `letta`? (docker in ubuntu )

**Additional context**

i downloaded "https://onedrive.live.com/view.aspx?resid=7B8BC7AAEBA7A500%2161548&authkey=!AP1942sZUGKvNdU"
i added it in letta 
i asked about how to install plex with zurg and then the error happend 

**Letta Config**
Please attach your `~/.letta/config` file or copy past it below.

where do  i find this using docker ?
---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

- [x] The exact model you're trying to use (qwen2.5:latest)
- [x] The local LLM backend you are using (Ollama)
- [x] Your hardware for the local LLM backend (local computer)

**Comment by sarahwooders** [comment]
Where did you see the error? On the server logs, or on the browser? 

I was able to upload you example into a data source and attach it to the agent's (the passages are in "Archival Memory") 

<img width="1312" alt="image" src="https://github.com/user-attachments/assets/e091e612-487a-4f0b-9c95-cd7a6f9c8894">

Maybe there is an issue specific to Ollama. Can you double check that the archival memories are successfully attached? You can do this by viewing the agent in the ADE.

**Comment by netixc** [comment]
It was in the browser and i asked it to look and show the code 
I had eveything in archival memory where around 38 passages and it worked like u did but when i asked code the error comes to the brozser and the agent becomes unusable
