### ISSUE TITLE
Docker usage, setting OpenAI Key in .env alone is not enough to get it to work.

### ISSUE THREAD

**Issue by mcapodici** [letta-ai/letta#1946]
**Describe the bug**

(Following steps on https://docs.letta.com/server/docker#run-letta-server-with-docker)

1. Clone Repo
2. Create .env with OPENAI_API_KEY="sk-..."
3. docker compose up
4. visit http://localhost:8083/agents
5. Click create agent
6. Model list is empty

Errors in console:
```
letta_server-1  |   File "/app/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
letta_server-1  |     raise HTTPError(http_error_msg, response=self)
letta_server-1  | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.openai.com/v1/models
```

8. kill docker compose
9. export OPENAI_API_KEY="sk-..."
10. docker compose up
11. visit http://localhost:8083/agents
5. Click create agent
6. Model list is populated

**Please describe your setup**
- [ ] How did you install letta?
  - Clone, Docker Compose (as above)
- [ ] Describe your setup
  - What's your OS (Windows/MacOS/Linux)? Windows 11
  - How are you running `letta`? Docker

NOTE: I am sure the server is reading the .env file because as soon as you add the key, it removes it from the list of "missing keys" in the console log.

**Comment by vojtapohunek** [comment]
The API key in .env shouldn’t be in “ “. The key isn’t being loaded properly.

**Comment by mcapodici** [comment]
I tried with and without quotes

**Comment by davidsells** [comment]
The quotes will not cause the problem.  I validated this by unsetting my shell variable ( unset OPENAI_API_KEY) and then used the .env file with a quoted key and it pulled in the models as normal.
