### ISSUE TITLE
Provide Letta LLM Leaderboards

### ISSUE THREAD

**Issue by distributev** [letta-ai/letta#2013]
So that people will clearly see which LLMs work well with Letta and which do not.

Similar idea with 

https://aider.chat/docs/leaderboards/

Meanwhile 'Berkeley Function-Calling Leaderboard' is good enough because it ranks LLMs based
on their ability to do Function-Calling (which is fundamental for Letta's well functioning)

https://gorilla.cs.berkeley.edu/leaderboard.html

Here you can see that GPT-4o-mini-2024-07-18 (FC) is a great choice for Letta because it ranks 4th and 
it has a very good price.

P.S - I lost a huge amount of time trying MemGPT/Letta with lots or random LLMs, 
including the "stars" LLMs, just to get back stack traces up to the level of almost giving up.

Until, by luck, I tried GPT-4o-mini and it worked great + when I saw the price I knew this is it.

**Comment by sarahwooders** [comment]
We just started working on this recently, so will have updates toon. Anecdotally, we've also seen `gpt-4o-mini` have great cost/performance generally recommend that.
