### ISSUE TITLE
Unable to run Letta v0.5

### ISSUE THREAD

**Issue by ArtificialFish** [letta-ai/letta#2020]
**Describe the bug**
I updated Letta to the latest version (I get the error below for all v0.5 however) and afterward received the error when running my code. I am now no longer able to run `letta run` or `letta server`. The issue persists if I follow the quickstart and install Letta in a completely new project. 

**Please describe your setup**
- Installed with `pip install letta`
- Windows 11
- Terminal

**Screenshots**
![image](https://github.com/user-attachments/assets/89fc6990-eb44-464d-a5aa-08c728af1c57)
![image](https://github.com/user-attachments/assets/51e05db4-4f93-4365-8dff-f45a28cda110)
![image](https://github.com/user-attachments/assets/354bdbef-1fda-4e3c-92be-fc2ef856eb5a)

**Comment by sarahwooders** [comment]
Could you please run: 
```
rm -r ~/.letta 
# export OPENAI_API_KEY=... or whatever other provider key 
letta run 
```

**Comment by ArtificialFish** [comment]
Looks like it works now, thanks!
