### ISSUE TITLE
A question about AgentState and Agent.

### ISSUE THREAD

**Issue by Nuclear6** [letta-ai/letta#2024]
I just started to study this project. I haven't fully understood it yet, but I feel it is a great project. However, when I executed the letta run command and understood the source code, I encountered a problem: 

in the source code of creating a new Agent in the cli.py, I understand that _client.create_agent_ is used to create an AgentState, and then use this AgentState to create an Agent, that is, _letta_agent = Agent()_. 

My question is, even if I want to create a letta agent later, why do I need to initialize an Agent when creating an AgentState? 
![image](https://github.com/user-attachments/assets/2d1b4033-6a30-485a-9928-790ec3e6143d)

**Comment by sarahwooders** [comment]
The `Agent` class instantiates an agent based off of the data in `AgentState` - `Agent` is the class while `AgentState` represents all the information you need to re-initialize an agent.
