### ISSUE TITLE
qdrant archival doesn't work

### ISSUE THREAD

**Issue by victorserbu2709** [letta-ai/letta#2025]
**Describe the bug**
Tried to setup letta with qdrant for archival memory and it doesnt work
**Please describe your setup**
- [ ] How did you install letta?
  - `pip install letta`?
- [ ] Describe your setup
Linux
  - How are you running `letta`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal)
Shell

I receive error at https://github.com/letta-ai/letta/blob/main/letta/agent_store/qdrant.py#L9
`
from letta.data_types import Passage, Record, RecordType
`

**Comment by cpacker** [comment]
Sorry for the confusion @victorserbu2709 - our `qdrant` integration if currently deprecated (that file is dead code and should be removed/disabled). If you want to use `qdrant` with Letta, we'd recommend accessing `qdrant` via a custom tool, eg a Python cool that imports their client and uses it to search a database: https://python-client.qdrant.tech/
