### ISSUE TITLE
Context window is not read in anthropic and summarize is not working

### ISSUE THREAD

**Issue by Sapessii** [letta-ai/letta#2044]
**Describe the bug**
Even setting the context window, the summarize function is not called. 

I think this happens because "summarize_messages_inplace" is called only when the llm returns error, but claude has 200k, it will take a lot to reach it

And when manually called throws error in anthropic.py here
`        assert len(response_json["content"]) == 2, response_json
`

**Letta Config**
Using anthropic with claude 3.5 sonnet latest

Let me know if you need further details,
Thank you!

**Comment by cpacker** [comment]
I believe this should be fixed in the latest version! Please reopen if not working.
