### ISSUE TITLE
Dropdowns are not scrollable, causing usability issues with large lists

### ISSUE THREAD

**Issue by rashidrashiii** [letta-ai/letta#2050]
**Describe the bug**
The dropdowns (e.g., for models) are not scrollable. When the number of items in the dropdown exceeds the visible space, it becomes impossible to access the hidden items without zooming out the browser window. This issue is not limited to model dropdowns; no dropdown menus in the application appear to support scrolling.

**Please describe your setup**

	•	How did you install Letta?
	•	git clone
	•	Describe your setup
	•	OS: macOS
	•	Running environment: Terminal

**Screenshots**

1. Normal screen ![without zoom](https://github.com/user-attachments/assets/3b73a15d-63a9-480d-a595-45fc78e92c07) 
2. While zooming out ![with zoomout](https://github.com/user-attachments/assets/39643392-c0fc-4201-93f3-df6c7e180b2a)

**Additional context**
This bug significantly impacts usability, especially when working with a large number of models. Adding scroll functionality to dropdown menus would greatly enhance the user experience.

**Comment by rashidrashiii** [comment]
Hi,

I have reported this bug and would like to work on resolving it. Could you please assign this issue to me?

Thank you!

**Comment by cpacker** [comment]
Fixed in ADE
