### ISSUE TITLE
Agent Last Run Is Always Showing as "Never"

### ISSUE THREAD

**Issue by cal88** [letta-ai/letta#2069]
**Describe the bug**

**Please describe your setup**
- [x ] How did you install letta?
  - git clone --branch main --single-branch https://github.com/letta-ai/letta.git
  - docker compose up
- [x ] Describe your setup
  - Linux Ubuntu
  - Terminal

**Screenshots**
![2024-11-20 17_24_00-45 121 147 87 - Remote Desktop Connection](https://github.com/user-attachments/assets/64b01f8e-7c37-4f0e-a7a9-b85e7c47c46b)

**Additional context**
Issue persists even after stop start of docker.

**Letta Config**
No changes done to `~/.letta/config` file.

**Comment by sarahwooders** [comment]
Thanks for reporting this - we have a updated version of the ADE coming out soon (1-2 weeks) so this will be fixed in that release.

**Comment by cal88** [comment]
Nice! Looking forward to it. Thank you.
