### ISSUE TITLE
Deploy Letta Server behind reverse proxy

### ISSUE THREAD

**Issue by edoardoramalli** [letta-ai/letta#2107]
Is there a way to deploy the Letta server behind a reverse proxy, thus changing the base URL?

**Comment by cpacker** [comment]
What exactly do you mean by a reverse proxy in this case? You can set the port using `--port` when you run `letta server`, but Letta itself will just run on localhost. If you want to expose the server with a static IP you could try ngrok or use a standard deployment stack w/ Docker. (please reopen if needed)
