### ISSUE TITLE
Letta requires Python versions <3.13, >=3.10

### ISSUE THREAD

**Issue by nusret35** [letta-ai/letta#2120]
I can't install letta's latest version 0.5.5 since I am using Python 3.13 . I have no intentions of downgrading my Python version. Why is it necessary? In order to make this framework more accessible to bigger masses, it should support the latest version of Python.

<img width="1295" alt="Screenshot 2024-11-29 at 02 14 38" src="https://github.com/user-attachments/assets/a4bd826f-144f-4eab-bfa4-67e1058577f8">

**Comment by sarahwooders** [comment]
Hi @nusret35 - thanks for reporting this. We will try to add 3.13 support as soon as possible, though we are also constrained by whether the packages we depend on support 3.13.

**Comment by nusret35** [comment]
Hello @sarahwooders, thank you for your response! I’ll also look into it and see what can be done.

**Comment by sarahwooders** [comment]
We just added support!
