### ISSUE TITLE
Unable to create an agent in the ADE

### ISSUE THREAD

**Issue by T-ravis-H** [letta-ai/letta#2212]
**Describe the bug**
from localhost:8283/agents ; click on the "+ Create Agent" button, The "Create Agent" modal pops up, make any changes you want (that are valid (i.e., the agent name must be 2 characters, fill in all the fields, model, embedding Config, select template for Agent and human, click create nothing displays in the browser, I see a 422 thrown "INFO:     ::1:62369 - "POST /v1/agents/ HTTP/1.1" 422 Unprocessable Entity"

My cursor AI says this about the error 

"The issue is that the ADE web app is using an outdated API schema. The agent creation endpoint has changed:
1. It now requires a memory_blocks field
The old memory field structure is no longer accepted
Looking at the server code earlier, I can see that the memory system has been refactored to use a block-based approach. This is why we're seeing those warnings in the server log about duplicate operation IDs for memory block operations.
To fix this, you have a few options:
1. Update the ADE web app code to use the new API schema"

**Please describe your setup**
- [ ] How did you install letta?
  - `pip install letta` into a .venv in my codebase
- [ ] Describe your setup
  - What's your OS Win11
  - How are you running `letta` cmd: letta server --debug

**Screenshots**

**Additional context**

**Letta Config**
v0.6.1

---

Using OpenAI various models

**Comment by cpacker** [comment]
Hi @T-ravis-H ,

The old ADE is no longer supported beyond Letta version `0.5.0` (as you correctly noted, the APIs changed and the old ADE was not updated to the new API schema).

The new ADE that is under active development is available [here](https://app.letta.com). That one is fully up-to-date with the API schemas and can connect to your localhost (you can even configure it to connect to multiple Letta server instances behind static IPs).
