### ISSUE TITLE
ARM64 Docker image support

### ISSUE THREAD

**Issue by AliSayyah** [letta-ai/letta#2242]
**Is your feature request related to a problem? Please describe.**
I need to build the docker image on my Arm64 machine manually. Using the image in the docker-hub fails because it only supports AMD64 architecture.
**Describe the solution you'd like**
If it's ok with you, I can add platform-specific docker builds to the CI/CD pipeline.

**Comment by cpacker** [comment]
Definitely open to reviewer PRs with improvements to our Dockerfile!

**Comment by AliSayyah** [comment]
Merged
