### ISSUE TITLE
llama-index-embeddings-ollama missing from docker that gets pulled when you use the existing compose.yml file

### ISSUE THREAD

**Issue by TOoSmOotH** [letta-ai/letta#2258]
**Describe the bug**
llama-index-embeddings-ollama is missing from the docker letta server docker container. 

**Please describe your setup**
- [ ] How did you install letta?
  - Using the compose file. 
- [ ] Describe your setup
  - Linux and docker.
 
If you install llama-index-embeddings-ollama via pip while the container is running then embeddings work properly.

**Comment by sarahwooders** [comment]
Sorry this will be fixed with #2264 - we moved off of that package but I think a code diff got missed.
