### ISSUE TITLE
Agents' replied message not seen in ADE

### ISSUE THREAD

**Issue by lemorage** [letta-ai/letta#2291]
**Describe the bug**
I am interacting with my newly created agent in ADE, and it never replies to me. But it seemed it thought it had replied.

Step to reproduce:
1. Create a new agent
```
  agent_state = client.create_agent(
      name="yanara",
      memory=ChatMemory(
          human="Name: Sarah",
          persona=YANARA_PERSONA,
      ),
      system=gpt_system.get_system_text("memgpt_chat"),
      include_base_tools=True,
  )
  ```
  
2. run `letta server` on local and open ADE
3. chat with the agent, but no replies (shown in screenshot)

**Please describe your setup**
- [X] How did you install letta?
  - `pip install letta`
- [X] Describe your setup
  - What's your OS? **MacOS**
  - How are you running `letta`?  **Terminal**

**Screenshots**
<img width="553" alt="agent not replying" src="https://github.com/user-attachments/assets/5600490b-a596-4e75-8ab8-c5df0e4e9efa" />

**Additional context**

**Letta Config**
Please attach your `~/.letta/config` file or copy paste it below.
```
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[archival_storage]
type = chroma
path = /Users/clannad/.letta/chroma

[recall_storage]
type = sqlite
path = /Users/clannad/.letta

[metadata_storage]
type = sqlite
path = /Users/clannad/.letta

[version]
letta_version = 0.6.5
```

**Comment by lemorage** [comment]
Update:

I used the following code to send a message to my agent (another newly created one), and print out its response. Surprisingly, it indeed sent me a welcome message, but I just could not see it in ADE.

```py
reply = client.send_message(agent_id=agent_state.id, message="Hey, how are u?", role="user")
print(reply)
```
Printed response:
```py
LettaResponse(
    messages=[
        InternalMonologue(
            id='message-682d25ac-66fb-4a2f-95ab-48c206ea8168',
            date=datetime.datetime(2024, 12, 20, 4, 37, 47, 801492, tzinfo=datetime.timezone.utc),
            message_type='internal_monologue',
            internal_monologue='Ensuring that my tone remains warm and professional as per my persona attributes.'
        ),
        FunctionCallMessage(
            id='message-682d25ac-66fb-4a2f-95ab-48c206ea8168',
            date=datetime.datetime(2024, 12, 20, 4, 37, 47, 801492, tzinfo=datetime.timezone.utc),
            message_type='function_call',
            function_call=FunctionCall(
                name='send_message',
                arguments='{\n  "message": "Hello Sarah, I\'m doing well, thank you! How can I assist you with your hotel booking today?"\n}',
                function_call_id='call_sTaVwf9aV9IN73AlY2hmGYLr'
            )
        ),
        FunctionReturn(
            id='message-6a716e05-92c5-4b14-8fa4-1876eb0bb6d9',
            date=datetime.datetime(2024, 12, 20, 4, 37, 47, 808970, tzinfo=datetime.timezone.utc),
            message_type='function_return',
            function_return='{\n  "status": "OK",\n  "message": "None",\n  "time": "2024-12-20 12:37:47 PM CST+0800"\n}',
            status='success',
            function_call_id='call_sTaVwf9aV9IN73AlY2hmGYLr',
            stdout=None,
            stderr=None
        )
    ],
    usage=LettaUsageStatistics(completion_tokens=59, prompt_tokens=2696, total_tokens=2755, step_count=1)
)
```
However in ADE:
<img width="557" alt="ADE-no_reply" src="https://github.com/user-attachments/assets/71433e04-98f8-4d3d-9741-0306a0939763" />

**Comment by mlhommet** [comment]
I have the same issue - fresh local install
 
![image](https://github.com/user-attachments/assets/e87cef40-e821-4adf-a0c5-e5d2c7c25180)

**Comment by sinhprous** [comment]
same issue, can use the Python sdk to send and receive message but the replies don't appear in the ADE

**Comment by cpacker** [comment]
Sorry @lemorage / @mlhommet / @sinhprous - this is a bug in the frontend due to a breaking API change (it's purely UI, backend is fine), will be fixed very soon / later today! Will update you all once it's ready.
