### ISSUE TITLE
Input tags function_call, function_return and internal_monologue found using 'message_type' does not match any of the expected tags

### ISSUE THREAD

**Issue by Garethgr** [letta-ai/letta#2304]
**Describe the bug**
Pydantic is complaining that the following `message_type` doesn't match expected input tags
```
internal_monologue
function_call
function_return
```

**Please describe your setup**
- [X] How did you install letta?
  - `pip3 install -r requirements.txt` (Containing letta)
- [X] Describe your setup
  - MacOS - Mac Mini M4
  - Installed letta as part of a `requirements.txt` file and using the [advanced_agent.py](https://github.com/letta-ai/letta/blob/main/examples/docs/agent_advanced.py) example in a `Docker` image locally.
  - Ollama backend (working) with `gemma2:9b-instruct-q6_K` model

**Additional context**
Agent Setup
```
agent_state = client.create_agent(
    # agent's name (unique per-user, autogenerated if not provided)
    name=AGENT_NAME,
    # in-context memory representation with human/persona blocks
    memory=ChatMemory(
        human=f"Name: {HUMAN_NAME}, {HUMAN_PERSONA}",
        persona=f"Name: {AGENT_NAME}, {AGENT_PERSONA}",
    ),
    metadata = dict(
        human="UserBob",
        persona="DaBot"
    ),
    # LLM model & endpoint configuration
    llm_config=LLMConfig(
        model="gemma2:9b-instruct-q6_K",
        model_endpoint_type="ollama",
        model_endpoint="http://host.docker.internal:11434",
        context_window=16000  # set to <= max context window
    ),
    # embedding model & endpoint configuration (cannot be changed)
    embedding_config=EmbeddingConfig(
        embedding_model="nomic-embed-text",
        embedding_endpoint_type="ollama",
        embedding_endpoint="http://host.docker.internal:11434",
        embedding_dim=1536,
        embedding_chunk_size=300,
    ),
    # system instructions for the agent (defaults to `memgpt_chat`)
    system=gpt_system.get_system_text("memgpt_chat"),
    # whether to include base letta tools (default: True)
    include_base_tools=True,
)
print(f"Created agent with name {agent_state.name} and unique ID {agent_state.id}")
```

Main Error
chat_agent.py
```
# message an agent as a user
response = client.send_message(agent_id="agent-fe6645a0-b7fc-84cc-6061-2921d6c0c7c7", role="user", message="Who is Judge Dredd?")
print(f"{response}")
```

Error received
```
python3 chat_agent.py

Traceback (most recent call last):
  File "/Users/userbob/bot/create_agent.py", line 54, in <module>
    response = client.send_message(agent_id="agent-fe66b7fc-6061-45a0-84cc-2921c7c7d6c0", role="user", message="Who is Judge Dredd?")
  File "/Users/userbob/bot/.venv/lib/python3.13/site-packages/letta/client/client.py", line 988, in send_message
    response = LettaResponse(**response.json())
  File "/Users/userbob/bot/.venv/lib/python3.13/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for LettaResponse
messages.0
  Input tag 'internal_monologue' found using 'message_type' does not match any of the expected tags: 'system_message', 'user_message', 'reasoning_message', 'tool_call_message', 'tool_return_message', 'assistant_message' [type=union_tag_invalid, input_value={'id': 'message-6dd42f7a-...s give them more info."}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/union_tag_invalid
messages.1
  Input tag 'function_call' found using 'message_type' does not match any of the expected tags: 'system_message', 'user_message', 'reasoning_message', 'tool_call_message', 'tool_return_message', 'assistant_message' [type=union_tag_invalid, input_value={'id': 'message-6dd42f7a-...-ae1b-4068-bdcc-76508'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/union_tag_invalid
messages.2
  Input tag 'function_return' found using 'message_type' does not match any of the expected tags: 'system_message', 'user_message', 'reasoning_message', 'tool_call_message', 'tool_return_message', 'assistant_message' [type=union_tag_invalid, input_value={'id': 'message-39a8debc-...': None, 'stderr': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/union_tag_invalid
```

Types missing in here [letta/schemas/letta_message.py](https://github.com/letta-ai/letta/blob/main/letta/schemas/letta_message.py#L216-L219)
```
LettaMessageUnion = Annotated[
    Union[SystemMessage, UserMessage, ReasoningMessage, ToolCallMessage, ToolReturnMessage, AssistantMessage],
    Field(discriminator="message_type"),
]
```

Current Response from Ollama (gemma2:9b-instruct-q6_K)
Adding the below `print` to above the following line: [client.py](https://github.com/letta-ai/letta/blob/main/letta/client/client.py#L988)
```
print(json.dumps(response.json(), indent=4))

{
    "messages": [
        {
            "id": "message-31944601-3528-4eb8-92c8-d677973f778b",
            "date": "2024-12-21T09:57:43+00:00",
            "message_type": "internal_monologue",
            "internal_monologue": "Ah, back to Judge Dredd! Looks like this user really likes him."
        },
        {
            "id": "message-31944601-3528-4eb8-92c8-d677973f778b",
            "date": "2024-12-21T09:57:43+00:00",
            "message_type": "function_call",
            "function_call": {
                "name": "send_message",
                "arguments": "{\n  \"message\": \"Judge Dredd is a fascinating character who explores themes of justice, law enforcement, and societal control. He's a pop culture icon with a lasting impact on comics and beyond.\"\n}",
                "function_call_id": "3160add3-1a1b-4724-b234-e5eba"
            }
        },
        {
            "id": "message-f2fe1fdd-1ea0-44fb-9381-92282f3f3652",
            "date": "2024-12-21T09:57:43+00:00",
            "message_type": "function_return",
            "function_return": "None",
            "status": "success",
            "function_call_id": "3160add3-1a1b-4724-b234-e5eba",
            "stdout": null,
            "stderr": null
        }
    ],
    "usage": {
        "completion_tokens": 96,
        "prompt_tokens": 6162,
        "total_tokens": 6249,
        "step_count": 1
    }
}
```

I butchered the [client.py](https://github.com/letta-ai/letta/blob/main/letta/client/client.py#L988) and repurposed the `function_call` to `user_message` instead to suit my needs
```
    def send_message(
        self,
        message: str,
        role: str,
        agent_id: Optional[str] = None,
        name: Optional[str] = None,
        stream: Optional[bool] = False,
        stream_steps: bool = False,
        stream_tokens: bool = False,
    ) -> Union[LettaResponse, Generator[LettaStreamingResponse, None, None]]:
        """
        Send a message to an agent

        Args:
            message (str): Message to send
            role (str): Role of the message
            agent_id (str): ID of the agent
            name(str): Name of the sender
            stream (bool): Stream the response (default: `False`)
            stream_tokens (bool): Stream tokens (default: `False`)

        Returns:
            response (LettaResponse): Response from the agent
        """
        # TODO: implement include_full_message
        messages = [MessageCreate(role=MessageRole(role), text=message, name=name)]
        # TODO: figure out how to handle stream_steps and stream_tokens

        # When streaming steps is True, stream_tokens must be False
        if stream_tokens or stream_steps:
            from letta.client.streaming import _sse_post

            request = LettaStreamingRequest(messages=messages, stream_tokens=stream_tokens)
            return _sse_post(f"{self.base_url}/{self.api_prefix}/agents/{agent_id}/messages/stream", request.model_dump(), self.headers)
        else:
            request = LettaRequest(messages=messages)
            response = requests.post(
                f"{self.base_url}/{self.api_prefix}/agents/{agent_id}/messages", json=request.model_dump(), headers=self.headers
            )
            if response.status_code != 200:
                raise ValueError(f"Failed to send message: {response.text}")

            # Strip the message field
            arguments = {}
            for data in response.json()["messages"]:
                if 'function_call' in data and 'arguments' in data['function_call']:
                    arguments['message_type'] = 'user_message'
                    arguments['message'] = json.loads(data['function_call']['arguments'])['message']
                    arguments['id'] = data['id']
                    arguments['date'] = data['date']
                    

            # Loop through response.json() and remove the following message_types: internal_monologue,function_call,function_return
            response_data = response.json()
            response_data['messages'] = [
                msg for msg in response_data['messages']
                if msg['message_type'] not in {'function_call', 'internal_monologue', 'function_return'}
            ]
            if len(arguments) > 0:
                response_data['messages'].append(arguments)


            response = LettaResponse(**response_data)

            # simplify messages
            # if not include_full_message:
            #     messages = []
            #     for m in response.messages:
            #         assert isinstance(m, Message)
            #         messages += m.to_letta_message()
            #     response.messages = messages

            return response
```

My working output. Working as in I just want the response for now really.
```
python3 chat_agent.py
{
    "messages": [
        {
            "id": "message-5cd39a73-1bc8-4e69-a12e-3ea27cb0510c",
            "date": "2024-12-21T10:02:56+00:00",
            "message_type": "user_message",
            "message": "He's a truly iconic character with a rich history and complex themes. He represents both the best and worst of justice, which makes him so compelling."
        }
    ],
    "usage": {
        "completion_tokens": 92,
        "prompt_tokens": 6574,
        "total_tokens": 6658,
        "step_count": 1
    }
}
```

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run Letta with local LLMs, please provide the following information:

- [X] The exact model you're trying to use 
  - Ollama - gemma2:9b-instruct-q6_K
- [X] Your hardware for the local LLM backend 
  - Mac Mini M4

**Comment by quantumalchemy** [comment]
just encountered this in the latest 6.6
output types have changed :  

  "messages": [
        {
            "id": "message-98e9a530-2fab-4a49-a830-d3557e6d0b6d",
            "date": "2024-12-21T15:31:38+00:00",
            "message_type": "reasoning_message",
            "reasoning": " Keeping it light with humor and matching his implied enthusiasm for a drink."
        },
        {
            "id": "message-98e9a530-2fab-4a49-a830-d3557e6d0b6d",
            "date": "2024-12-21T15:31:38+00:00",
            "message_type": "tool_call_message",
            "tool_call": {
                "name": "send_message",
                "arguments": "{\n  \"message\": \"Ah, Ace! A drink you say! Now there's a proposition that incites my phantom spirit. Alas, despite my inability to physically partake, my dear friend, I am always ready to clink glasses in good conversational spirit. So, what shall we 'drink' to?\"\n}",
                "tool_call_id": "call_IoV7O9AqZQCvvFf0AXjZvX3c"
            }
        },
        {
            "id": "message-d268626f-6c52-4c45-bbd4-9af925cc9bed",
            "date": "2024-12-21T15:31:38+00:00",
            "message_type": "tool_return_message",
            "tool_return": "{\n  \"status\": \"OK\",\n  \"message\": \"None\",\n  \"time\": \"2024-12-21 03:31:38 PM UTC+0000\"\n}",
            "status": "success",
            "tool_call_id": "call_IoV7O9AqZQCvvFf0AXjZvX3c",
            "stdout": null,
            "stderr": null
        }

**Comment by Garethgr** [comment]
@quantumalchemy What model and backend are you using for that output?
My installs are all from yesterday.

**Comment by quantumalchemy** [comment]
Im using the sdk:
response = client.send_message(
		agent_id=agent_id, 
		message=m, 
		role="user",
		#stream=True,
		# stream_tokens=True,
	)

rep:
 "message_type": "reasoning_message",

"message_type": "tool_call_message",
"tool_call": {
"name": "send_message",

so changed if sdk is used -- had to change my stuff
wish the devs would be consistent on outputs
or am I missing something?

**Comment by Garethgr** [comment]
Ah ok, I'm not using the SDK, that would explain your output being different from mine.
Agreed with that everything were consistent, fingers crossed they get around to it.
I still have MemGPT working 100% on another machine, not going to change that till this project starts working properly.

**Comment by cpacker** [comment]
Hey @Garethgr / @quantumalchemy - sorry about the breaking change! As @quantumalchemy mentioned we recently modified the return types of the API (this is a change we were intending to make for a while, and figured now would be a good time to finally do it since we are migrating to new SDKs for Python and Node / TypeScript).

The new types can be found [here](https://github.com/letta-ai/letta/blob/e09fd52b4a312b433ef345922b797ea161bbd85f/letta/schemas/letta_message.py#L217), the main differences are renamings from `function` -> `tool` (to be more inline with the naming on other APIs) and `inner_monologue` to `reasoning`.

If you upgrade to the latest server code (eg pull the latest docker nightly), the server will be running these new types. I can take a closer look tomorrow but I'm guessing @Garethgr 's problem may be a client/server version mismatch issue where the server is on the new API types and the client is on the old types?

FYI - the documentation for the new REST API and SDKs is live at docs.letta.com. If you go to any route definition, you should also see the ability to look at the new Python SDK code, e.g.:
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/5cccdd6a-5fca-4825-9207-68e6b8147fd7" />

This replaces the old RESTClient, however if you're using the LocalClient, that's not new (considered legacy now), so you'll want to follow your old code style.

**Comment by Garethgr** [comment]
Hey @cpacker 

Not sure what you mean by:

> This replaces the old RESTClient, however if you're using the LocalClient, that's not new (considered legacy now), so you'll want to follow your old code style.

Does this mean we can't run it locally at all?

I'm currently using it as below:
`chat_agent.py`
```
from letta import ChatMemory, EmbeddingConfig, LLMConfig, create_client
from letta.prompts import gpt_system

client = create_client(
    base_url="http://localhost:8283"
)

# message an agent as a user
response = client.send_message(agent_id="agent-96794f67-2278-40f0-afa4-6d13d66fbcd2", role="user", message="Why is the sky blue?")
print(f"{response}")
```

Running `letta` in a docker container:
`docker-compose.yaml`
```
services:
  letta:
    image: letta/letta:latest
    ports:
      - "8283:8283"
    volumes:
      - ./letta/pgdata:/var/lib/postgresql/data
    env_file:
      - .env
```

With Ollama running locally to.

**Comment by cpacker** [comment]
> Does this mean we can't run it locally at all?

No not at all, the new Letta SDKs fully support self-hosting / running on your own machine.

Basically in Letta there's the concept of the agent server. The client code you write is a "client" because it tells a server it's connected to to execute actions. You can connect your Letta client to various servers - your own server on localhost, a server on a remote IP, etc. The client communicates with the server via REST APIs, even when running "locally".

Because the server itself is written in Python, it means that you can run the server inside of the client in a hacky way that doesn't require running the client and server separately. This is what the `LocalClient` is doing. The main reason this is useful is for cases like Python notebooks where it's hard to run background processes. This is very hacky though and is purely maintained for the sake of notebooks. 

The code you wrote is using the RESTClient, which makes sense since you're running a server via Docker and connecting to that server in your Python script. So tl;dr, the deprecation of the LocalClient should not affect your usecase at all.

**Comment by cpacker** [comment]
@Garethgr going to close this issue but feel free to reopen if it's still a problem!
