### ISSUE TITLE
Configurable data store .memgpt 

### ISSUE THREAD

**Issue by agiletechnologist** [letta-ai/letta#329]
**Is your feature request related to a problem? Please describe.**
As a user of MemGPT, I would like to be able to set the location of file storage so that it can be placed outside of the user directory or home directory. 

**Describe the solution you'd like**
Use Configure or Command line options to set and use the directory where .memgpt is to be located. The default can remain if not specified in the user's home directory. 

**Additional context**
I have a suggestion to add an option or config to set the ".memgpt" location for storage. Here is a specific use case I have seen in production systems on Windows Server. They tend to put the C: drive for the Operating System and user to be small and often use D: E: and F: for data storage. Also, on Linux production servers, the /home is small, so on Linux production servers, the /home is small, and data stores are often mounted in other mount points. There are two reasons this is done: Security and separation of data from OS.  

Setting the data and configuration storage location should be configurable or specified on CLI.
The config could remain in the home directory for reading the config at load.

**Comment by Anrock** [comment]
Would be nice if memgpt adhered to XDG directory standard without a need to manually specifying memgpt-specific env vars or configs.

**Comment by agiletechnologist** [comment]
That only changes the config file path not MEMGPT_DIR the data remains in that dir.  That does not solve the overall storage issue.
