### ISSUE TITLE
Llava for llamacpp?

### ISSUE THREAD

**Issue by Drake-AI** [letta-ai/letta#330]
I don't know if it is an interesting feature to add llava support to send images in memgpt to llamacpp using llava models. I'm playing with it so let me know if it is suitable for this project.

**Comment by cpacker** [comment]
I think this would be a cool feature

**Comment by Drake-AI** [comment]
Working on it.

**Comment by cpacker** [comment]
> I think this would be a cool feature

(to expand on this, image support would really shine once we add a default GUI / chat UI alternative to the CLI, which is on the immediate roadmap)

**Comment by ProjCRys** [comment]
Could they add a flag like /giveimg and put the directory of the image to the CLI as a temporary test?

**Comment by Drake-AI** [comment]
> > I think this would be a cool feature
> 
> (to expand on this, image support would really shine once we add a default GUI / chat UI alternative to the CLI, which is on the immediate roadmap)

Agree. I will make the basic support for the CLI, easy to apply to a GUI later. 

> Could they add a flag like /giveimg and put the directory of the image to the CLI as a temporary test?

Just in the message, no commands needed.

**Comment by Drake-AI** [comment]
Ready to test in this PR https://github.com/cpacker/MemGPT/pull/357
