### ISSUE TITLE
Add hybrid/text search for archival memory

### ISSUE THREAD

**Issue by sarahwooders** [letta-ai/letta#362]
Text search might better than low quality embeddings. We can implement another `ArchivalMemory` (similar to `EmbeddingArchivalMemory`) that uses text-based/hybrid search.

**Comment by ohickl** [comment]
I'm interested in achieving as accurate an archival memory as possible, primarily to interact with my scientific literature in a dynamic and intuitive way. Wouldit make sense to be able to fine-tune the quality of the embeddings and adjust the parameters of the generation models? Currently, `BAAI/bge-small-en-v1.5` is in use, and I'm not overly familiar with the trade-offs between size and performance. Would upgrading to the larg version notably improve the results?"
