### ISSUE TITLE
Add Configuration and CLI Backoff settings for API Calls

### ISSUE THREAD

**Issue by agiletechnologist** [letta-ai/letta#376]
**Is your feature request related to a problem? Please describe.**
As a MemGPT User, I would like to have standard configuration options, and CLI overrides so that when I am loading Directories with recursion, which will easily reach the API Call limit, I can be adjusted for long loading times (perhaps even days) because of API Call limits. 

- The first use case is while loading many documents for archival.
- The second is during research, where that sizeable archival memory is being searched to find an answer.

There could be other use cases where response time does not matter. Still, the final answer does matter; waiting for API limits to pass and continuing the process without losing work done up to this point is essential to researchers. 

**Describe the solution you'd like**

Add a configuration option for changing the default values for backoff. Also, allow for CLI overrides so these can be changed at runtime.

Options: 
\--initial-delay [float]  -- The number of seconds in a float value that will be a start delay for the first backoff
\--exponential-base [float]  -- The multiplier base used in the backoff. If --jitter-enable is set, a random float between 0 and 1 is added.
\--jitter-enable  -- Enables jitter for the exponential base as a multiplier --jitter-disable turns this off.
\--max-retries [int]  -- Sets the maximum retries for backoff 

```bash
# data load example: 
# initial delay of 62 seconds with an exponential factor of 2.5 plus a random number between 0 and 1 times the last delay 
memgpt load directory --name ResearchArchive --input-dir /path/to/research/documents --recursive --initial-delay 62.0 \
       --exponential-base 2.5 --jitter-enable --max-retries 100

# run the example with a fixed retry time. Retry time is every 62 seconds with default or configured retry count.
memgpt run --initial-delay 62 --exponential-base 1 --jitter-disable
```
Adding to configure the ability to set these in the configuration for use as default parameters. 

**Describe alternatives you've considered**
Currently, there is no way to change these other than editing the hardcoded settings.

**Comment by cpacker** [comment]
In your workflow, would there be a significant different to having these as command-line flags, vs something that you can edit inside of https://github.com/cpacker/MemGPT/blob/main/memgpt/constants.py?

**Comment by sarahwooders** [comment]
We can maybe add this as advanced configuration options? So we don't include them in `memgpt configure`, but move whats set in `constants.py` into the `~/.memgpt/config` file and allow users to do: 

```
memgpt set config request_initial_delay_s 62 
```

**Comment by agiletechnologist** [comment]
It would be better for a config file or as command line options. Most people don't need or have a need. Editing application code needs to be corrected, which will be wiped out at the next upgrade. Being outside of code makes more sense if it is not default.

**Comment by sarahwooders** [comment]
@cpacker @agiletechnologist can you give me a list of parameters and their default values that we want to add into the advanced config?

**Comment by agiletechnologist** [comment]
These are the defaults in code [memgpt/openai_tools.py](https://github.com/cpacker/MemGPT/blob/3df7989e64d16aacf3209ca39f9c3f3fce86d144/memgpt/openai_tools.py#L16):

initial_delay: float = 1,
exponential_base: float = 2,
jitter: bool = True,
max_retries: int = 20,
