### ISSUE TITLE
Archival memory/Memory issues

### ISSUE THREAD

**Issue by TheOnlyWiseJEDI** [letta-ai/letta#381]
Using: text-generastion-webui
Model: ehartford_dolphin-2.2-mistral-7b - not quantized
Installed: using pip install -r requirements
OS: Windows 10
Shell: cmd.exe
Python: Python 3.11.3
pymemgpt installed: yes
Hardware: 12th Gen i7 64GB/RAM, RTX3060 12GB RAM
LLM and MemGPT on same system

There seems to be a problem with the archival memory usage (it's not happening) since I updated to memgpt 1.8

![image](https://github.com/cpacker/MemGPT/assets/123831682/6829b5ee-9252-4023-b6d6-a6b6ad84648d)

Including this in case it's related, I see this often after a few pages of conversation it repeats:
![image](https://github.com/cpacker/MemGPT/assets/123831682/b870d408-ad7b-4a80-8996-185dbb1c35da)

**Comment by sarahwooders** [comment]
Could you double check your config `~/.memgpt/config` to make sure archival memory is set to local? You should see something like this: 
```
[archival_storage]
type = local
```
If that looks ok, when can you try re-running with `memgpt run --debug` and see if it outputs additional logs? 

Can you also check what happens if you run the `/memory` command?

**Comment by TheOnlyWiseJEDI** [comment]
config shows:
[archival_storage]
type = local

/memory works fine, the archival section is empty, any memory editing fails, core_memory_update/edit/etc, same with archival memory, I just get;  insert error RetryError[<Future at 0x204beff9310 state=finished raised AuthenticationError>]

**Comment by TheOnlyWiseJEDI** [comment]
trying --debug

**Comment by sarahwooders** [comment]
Could you show a screenshot of what happens with a core memory update?

**Comment by TheOnlyWiseJEDI** [comment]
lol this time it has no knowledge of that function, normally it reports the authentication error
![image](https://github.com/cpacker/MemGPT/assets/123831682/06629af4-f5ef-4176-b002-2aa3eabfe14b)

**Comment by TheOnlyWiseJEDI** [comment]
not sure if it's related but if you recall- after I updated yesterday, in another ticket I reported the following trouble and you told me to delete .memgpt/config to fix it
![image](https://github.com/cpacker/MemGPT/assets/123831682/4f2f3e7e-f2fe-46b5-b894-f9c9e4ce5339)

**Comment by TheOnlyWiseJEDI** [comment]
I found this in the output:  

 Incorrect API key provided: NULL. You can find your API key at
https://platform.openai.com/account/api-keys.

I am hosting locally and not using OpenAI, I will remove the env variable for OPENAI_API_KEY as I do not need it and set it as a 'just in case' since I saw it had a bearing on something else I was reading about I threw it in there. I'll remove it and start over and see what happens.

**Comment by TheOnlyWiseJEDI** [comment]
I now get this when I start without that env variable:

![image](https://github.com/cpacker/MemGPT/assets/123831682/0daa26f7-369c-4d93-b815-5a1f0a12aec7)

**Comment by TheOnlyWiseJEDI** [comment]
confirmed that webui is set as the BACKEND_TYPE
![image](https://github.com/cpacker/MemGPT/assets/123831682/00c133db-b08a-4163-a911-9f0775e4a051)

**Comment by cpacker** [comment]
> confirmed that webui is set as the BACKEND_TYPE ![image](https://user-images.githubusercontent.com/123831682/281512937-00c133db-b08a-4163-a911-9f0775e4a051.png)

The last few errors are from not having `OPENAI_API_BASE` set (https://memgpt.readthedocs.io/en/latest/webui/). Not sure about the archival memory error, that's odd, looking into it.

**Comment by sarahwooders** [comment]
Can you share whats in your `~/.memgpt/config` in the `[embedding]` section?

**Comment by TheOnlyWiseJEDI** [comment]
[embedding]
model = local
dim = 384
chunk_size = 300

**Comment by TheOnlyWiseJEDI** [comment]
cpacker, above you said:  The last few errors are from not having OPENAI_API_BASE set (you need both BACKEND_TYPE and OPENAI_API_BASE to be set, https://memgpt.readthedocs.io/en/latest/webui/). Not sure about the archival memory error, that's odd, looking into it.

This is untrue for me, both of those variables are and have been set - those errors are not caused by a lack of having those env vars set properly in my case. Also note that the OPENAI_API_KEY is one the I mentioned because --debug revealed the detail I posted above complaining that I do not have a valid API KEY

**Comment by sarahwooders** [comment]
Hm so I'm pretty confused why there would be any kind of authentication error, since everything should be done locally for the embeddings if thats what your config is set to. Could you try running with memgpt installed via `pip install pymemgpt-nightly` and see if you have the same issues?

**Comment by TheOnlyWiseJEDI** [comment]
ok sure, can I just run that in the current memgpt conda env?

**Comment by TheOnlyWiseJEDI** [comment]
btw. I had to restore the system env variable OPENAI_API_KEY=Null in order to run memgpt, without it I get the invalid API key error above and can't run memgpt at all.

**Comment by TheOnlyWiseJEDI** [comment]
I'm not sure if I should do this on top of my current install or not, waiting for confirmation from you. Also if you have Anydesk installed I can give you my ID so you can check it out for yourself

**Comment by sarahwooders** [comment]
Could you try: 
```
pip uninstall pymemgpt 
pip install -U pymemgpt-nightly
```

**Comment by TheOnlyWiseJEDI** [comment]
Things appear to be working, the archival memory is being populated without error, what should I do now?

**Comment by sarahwooders** [comment]
Are there any other problems? If not I can close this issue.

**Comment by TheOnlyWiseJEDI** [comment]
I 'think' things are working properly, will this nightly build become tomorrow's update? should I 'pip uninstall' it and normally install memgpt tomorrow?
