### ISSUE TITLE
Unable to remove attached data

### ISSUE THREAD

**Issue by TheOnlyWiseJEDI** [letta-ai/letta#407]
I am making this an issue ticket rather than a suggestion because, well it's an issue :)

I was talking with another user as I asked aloud in the support channel if anyone knew how we can remove the content we attach (uploaded docs etc) and they didn't know either. I scoured the documentation and readme's everywhere I could find them and checked --help and cannot find a means of doing this. It is a necessity as agreed by the other user I spoke with we need this ability as soon as it's convenient for you, please and thank you in advance.

**Comment by sarahwooders** [comment]
Yes there is indeed no way to do this... we need to make a few changes to how the data is stored (e.g. keep around metadata about what data source a stored embedding came from), so can probably add soon but not immediately.

**Comment by TheOnlyWiseJEDI** [comment]
ok np, is there a 'dirty' unrecommended way you might want to reveal in a DM on discord? lol 
I uploaded a 'webpage' and it turned out horribly (poor choice of web content), it's messy and I want it out of there if possible. I'm not using postgre btw.

**Comment by TheOnlyWiseJEDI** [comment]
I ended up having to create a new agent so for the moment I don't need to remove any uploaded data and thus do not need you to answer my previous question.

**Comment by Falven** [comment]
@TheOnlyWiseJEDI look under `%USERPROFILE%\.memgpt\`
specifically under agents, this is where the config file is kept, you can edit the json files.
