### ISSUE TITLE
Avoid conversational data loss across versions 

### ISSUE THREAD

**Issue by TheOnlyWiseJEDI** [letta-ai/letta#414]
Once again I am making an 'issue' ticket rather than a suggestion because this issue is an actual problem.

Because of the fact that this is a work in progress I have had to recreate agents repeatedly and I know this is to be expected however it results in a loss of MUCH time invested with the AI agent that is discarded since the conversation history is lost when it is necessary to create a new agent and restart communication all over again.

Whether it is now, while development is underway or later when things are more stable, I can see the need for a method of 'importing' conversation history from another existing agent. This would solve the problem and make it possible to  continue with the personality and conversation history of the Agent no longer being used. 

Please make this possible if you can.

**Comment by sarahwooders** [comment]
@TheOnlyWiseJEDI are you having trouble re-loading agents from previous version? Could you please share the error? 

I can try to add some backward compatibility with the old format for at least the non-archival memory (archival memory is a bit tricky since its been very buggy in the past).

**Comment by TheOnlyWiseJEDI** [comment]
Well the cause of the need to create a new agent varies greatly. In many cases, while getting help with an issue (error) I have been told to just make a new agent and try again. One of the more significant updates changed the structure of the agent (new folder arrangements etc) and this meant having to make another new agent. So far I have lost track of how many times I have had to make a new agent and start over. There have indeed been many issues with archival memory. I was just telling vivi about today's trouble with that and this led once again to the need for creating a new agent as we tried to troubleshoot. If there were a means of simply transferring conversation history to a new agent that would do the trick.

**Comment by sarahwooders** [comment]
Ok so I think we can maybe add a few things to solve this: 
* Add `memgpt_version` as a metadata field int the agent config, so we know what version of the code was used to checkpoint the last agent's state
* Add a `memgpt copy agent --src <agent1> --dest <agent2>` that allows for migrating conversational data between agents created under different versions -- if we make another major change to the agent checkpointing, we can implement support for cross-version agent state copying

**Comment by TheOnlyWiseJEDI** [comment]
Awesome! Thank you this sounds good.

**Comment by sarahwooders** [comment]
@TheOnlyWiseJEDI we added a version field to the agent config in this release, so if we change the format of the saved data or config in the future we can make sure the old agents can be translated into the new format. 

Are there agents from past versions you still want to recover? If so, could you share the error you're getting with them and maybe DM the agent config and saved state (or the format) to us?

**Comment by TheOnlyWiseJEDI** [comment]
I have refrained from investing too much time into the agent I last created so I'm good with letting it go and starting fresh for the moment. Going forward, if I have an agent I want to keep and the format has changed with a new update will the translation be automatic or how is it accomplished?
