### ISSUE TITLE
Took 18hrs to attach a CSV file of 7mb

### ISSUE THREAD

**Issue by hemanthaar** [letta-ai/letta#491]
I am trying to solve a use case to load a CSV file to archival memory and I followed the instructions as mentioned in the example_data.md file in my local pc. 
It took 18hrs to attach a 7mb CSV file with 100 columns and 6000 rows. Any reason why and point some directions for better response.

![image](https://github.com/cpacker/MemGPT/assets/74851652/81c563af-cb49-49bd-9da2-9ac298fb656b)

And I am using Azure Open AI to generate embeddings and GPT 4 for chat completions in configuration.

**Comment by sarahwooders** [comment]
Unfortunately there's no easy way around this unless we parallelize the embedding calls. What command did you use to load the CSV?
