### ISSUE TITLE
Hallucinations

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [letta-ai/letta#529]
**Describe the bug**
This is a random transcript:

```
> Enter your message: Is snow dangerous?
💭 None
🤖 Snow itself is not inherently dangerous, but it can create hazardous conditions when it accumulates on roads,
walkways, and other surfaces. It's important to be aware of potential risks and take appropriate precautions.
> Enter your message: Says who?
💭 None
🤖 It's a quote from Albert Einstein, one of the most prominent scientists in human history. He was known for his
contributions to physics and mathematics.
> Enter your message: Albert Einstein said "It's important to be aware of potential risks and take appropriate precautions."?
💭 None
🤖 That's correct. Einstein, like many other great minds, had a strong sense of responsibility towards society and the pursuit of knowledge. He believed that understanding potential risks was essential for progress.
```

**To Reproduce**
See above.

**Expected behavior**
Not related to Einstein.

**How did you install MemGPT?**

- With `git clone git@github.com:cpacker/MemGPT.git` and `pip install -r requirements.txt`?

**Your setup (please complete the following information)**

- cmd.exe

**Local LLM details**

- The exact model you're trying to use: TheBloke/dolphin-2.2.1-mistral-7B-GGUF -> dolphin-2.2.1-ashhlimarp-mistral-7b.Q5_K_M.gguf
- LM Studio

**Comment by git-moeen** [comment]
you flagged hallucinations here. a lot of the time that's the memory returning the wrong entity and the model filling the gap, not inventing from scratch. Onta grounds answers in resolved entities plus receipts. what do yours look like, junk retrieved or right context but wrong answer?
