### ISSUE TITLE
MemGPT Localllm autogen keeps coming up wih information outside of data source

### ISSUE THREAD

**Issue by CoderTom314** [letta-ai/letta#546]
I am using dolphin-2.2.1-mistral-7b.Q8_0.gguf with airoboros grammar wrapper. Despite setting the temperature to 0.01 in webui, and specifying use only data from archive memory, when trying to find and compose short fact passages, memgpt keeps coming up with fictional events, or real events not from data source.

This is the message to memgpt:

"Remember the following instructions: "
    "1) Work autonomously to come up with titles and write about as many distinct, non-repeated, intriguing operations or affairs from the cold war, one at a time without supervision\n"
    "2) Search your archival memory [data source archive name] to complete the tasks. Do Not use facts from other sources\n"
    "3) Do NOT make up information\n"
    "4) Print the output to screen in this format:\nTitle: catchy title\nIntroduction: this is the introduction bla bla bla ... (Minimum 200 words)\nParagraph 2: this is the paragraph 2 bla bla bla ... (Minimum 200 words)\nParagraph 3: this is the paragraph 3 bla bla bla ... (Minimum 200 words)\nEnding: this is the ending bla bla bla ... (Minimum 200 words)\nTakeaway or lessons: 1 sentence\nSource: Section from Book\n\n"
    "5) Also append results to a used titles list in archival memory such that you don't repeat\n"
    "6) Always save checkpoint of conversation state.\n"
    "7) Do NOT prompt the user for guidance. Work alone.\n"
    "Once you have memorized the above instructions, acknowledge, follow the instructions and get to work"

**Comment by cpacker** [comment]
Can you try with `gpt-4` and see if you still have the same issue? I'm asking to help discern if this is a problem with the way to instructions are being formatted / passed to MemGPT or if this is an issue with the model (or both).

If you don't have `gpt-4` access can you post the full script here or DM it to me on Discord so I can try and reproduce the problem?
