### ISSUE TITLE
assistants api

### ISSUE THREAD

**Issue by jbstanley2004** [letta-ai/letta#565]
Adding support to use http call function to gpt assistants would be HUGE.

**Comment by jbstanley2004** [comment]
Thanks for the reply Charles. I was attempting to add functionality to be
able to message existing assistants and get the response, but I was
experiencing issues with memgpt not not sending the correct info; mainly
the required headers. I will confess, I'm far from an experienced coder, so
I'm sure it was error on my part. Thanks again!

**Comment by pligor** [comment]
Hi @cpacker a thumbs up here regarding the solution number 2 that you proposed. For practical reasons, yes we need some sort of an API. Need to be sending messages to a MemGPT Agent (that indeed might have been created a long time ago as you mentioned) and getting responses programmatically
