### ISSUE TITLE
Allow linking of functions during chat

### ISSUE THREAD

**Issue by cpacker** [letta-ai/letta#577]
Right now if you want to add custom functions you have to define them ahead of time and load them via the preset.

TODO: allow functions to get linked during chat

**Comment by cpacker** [comment]
> > I think the most important implementation detail will probably on the UX side - how do we expect users to want to link/update functions mid-chat / in-between chat? What kind of CLI commands do we need to support this? Which agent state files do we need to write to to support this (to make sure the change persists across saves/loads).
> 
> Agreed, the mid chat UX is tricky.
> 
> Personally I was somewhat surprised that adding a function, adding it in the preset, and restarting the agent didn't result in the new function being added. The simplest thing to do might be to simply change the default behavior and pull the list of functions from the preset config rather than the state.
> 
> I can't really think of a reason you _wouldn't_ want to absorb functions that were defined for the preset you're using on an agent

maybe a good compromise here making a `/resync` command that syncs the function set back with the preset?

and maybe `/resync functions` for functions, `/resync system` for system prompt, etc., since at that point we might as well allow syncing more than just functions from the preset

**Comment by tombedor** [comment]
> > > I think the most important implementation detail will probably on the UX side - how do we expect users to want to link/update functions mid-chat / in-between chat? What kind of CLI commands do we need to support this? Which agent state files do we need to write to to support this (to make sure the change persists across saves/loads).
> > 
> > 
> > Agreed, the mid chat UX is tricky.
> > Personally I was somewhat surprised that adding a function, adding it in the preset, and restarting the agent didn't result in the new function being added. The simplest thing to do might be to simply change the default behavior and pull the list of functions from the preset config rather than the state.
> > I can't really think of a reason you _wouldn't_ want to absorb functions that were defined for the preset you're using on an agent
> 
> maybe a good compromise here making a `/resync` command that syncs the function set back with the preset?
> 
> and maybe `/resync functions` for functions, `/resync system` for system prompt, etc., since at that point we might as well allow syncing more than just functions from the preset

works for me, would it be ok to add the `/resync functions` as a standalone pr and leave the rest with a `NotImplementedError`

**Comment by cpacker** [comment]
yeah that sounds good!

**Comment by angrysky56** [comment]
I found this, not sure if it helps-

Auto Generated Agent Chat: Function Inception
In this notebook, we demonstrate how to use `AssistantAgent` and `UserProxyAgent` to give them the ability to auto-extend the list of functions the model may call. Functions need to be registered to `UserProxyAgent`, which will be responsible for executing any function calls made by `AssistantAgent`. The assistant also needs to know the signature of functions that may be called. A special `define_function` function is registered, which registers a new function in `UserProxyAgent` and updates the configuration of the assistant.

In the example scenario, the user first asks to define a function that gets a URL and prints the response body. Then the user asks to print the response body, and the assistant suggests to the user to call the new function.

https://github.com/microsoft/autogen/blob/main/notebook/agentchat_inception_function.ipynb
