### ISSUE TITLE
Missing python module for loading .pdf files. with memgpt load directory

### ISSUE THREAD

**Issue by agiletechnologist** [letta-ai/letta#590]
**Describe the bug**

When loading directories with many common file types:
` File "/home/max/MemGPT/venv/lib/python3.11/site-packages/llama_index/readers/file/docs_reader.py", line 25, in load_data
    raise ImportError(
ImportError: pypdf is required to read PDF files: pip install pypdf

works properly after pip install pypdf
`
**Please describe your setup**

- [x] MemGPT version: 0.2.6
- [x] How did you install memgpt? `pip install pymemgpt`
- [x] Describe your setup
  - What's your OS: Windows 11 and Debian Linux 
  - How are you running `memgpt`? Multiple `cmd.exe`, Powershell, Terminal

**Comment by cpacker** [comment]
Hmm this is odd - `pypdf` should be inside the package: https://github.com/cpacker/MemGPT/blob/main/pyproject.toml#L50

@sarahwooders any idea why this might not be getting picked up? Or possible error during install?
