### ISSUE TITLE
Better contributor guidelines

### ISSUE THREAD

**Issue by cpacker** [letta-ai/letta#645]
**Is your feature request related to a problem? Please describe.**

Make it easier for people looking to contribute to get started. Should target both programmers and non-programmers.

Documentation:
- [x] Add new "contribute to memgpt!" docs page, with information on:
- [ ] What our current main roadmap is
- [ ] How to find good things to work on (using github labels + discord)
- [x] For non-programmers, an example on how to contribute to the documentation just using github features 
- [x] For programmers, can link to CONTRIBUTING.md, which is where we can store information on making PRs with forks

GitHub organization:
- [ ] Make better use of labels/tags
- [ ] Have a "contributor" project viewer so people can self-assign etc

**Comment by cpacker** [comment]
Feel free to add TODOs/feedback and I can work them in, @goetzrobin @agiletechnologist @danx0r etc

**Comment by cpacker** [comment]
Comment from @gepf on Discord:

> I think that issue is a good start to bootstrapping that effort. Issues & labels, plus what to expect. What does a good PR look like? Highlighting standards, best practices, etc., plus pointers to some of GitHub's resources for people who've never contributed via fork/PR (includes a surprising amount of people who are not newbies but haven't contributed to projects outside work or school)

**Comment by cpacker** [comment]
via @goetzrobin: considering update github PR template:
- current: https://github.com/cpacker/MemGPT/blob/main/.github/pull_request_template.md
- proposed (for inspiration): https://github.com/goetzrobin/spartan/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by galeep** [comment]
Welcoming localized docs/translations as well - even if not a focus, it is low-hanging fruit that helps expand the project's reach, and makes a `great first issue` :)

**Comment by agiletechnologist** [comment]
Language filters on templates are for system, persona, and human. And some functions are written for AIs trained in other languages. 
I think Multi Lingual is the way to go. perhaps specific language like anna_pa.en-US.txt

**Comment by cpacker** [comment]
I did a bit of revising of the contributor guide, still could use some work (good first issue ;)): https://memgpt.readme.io/docs/contributing
