### ISSUE TITLE
Milvus Support

### ISSUE THREAD

**Issue by MiddleSand** [letta-ai/letta#672]
**Is your feature request related to a problem? Please describe.**
Milvus is a standalone vector database that is well-respected in the industry. MemGPT support for Milvus - as a datasource, or a storage format - would improve the quality and utility of the product.

**Describe the solution you'd like**
A Milvus integration for MemGPT allowing its utilization as a storage backend, datasource, and an agent repository.

**Describe alternatives you've considered**
Potentially one could write or find a mock SQL syntax wrapper around Milvus to pretend to be Postgres - but that would get unruly and slow quickly.

**Additional context**
Milvus project website: https://milvus.io/
Milvus documentation: https://milvus.io/docs 

If this is not an interest of the developers or they do not have the time, I can attempt to write and PR a basic implementation.

**Comment by cpacker** [comment]
@MiddleSand adding Milvus would be great, and a great community PR if you're up for it!

We have a pending storage refactor (#566) that affects the way the storage connectors are written, so if you start writing a PR for this definitely follow the code on that branch (eg, follow the code for the chroma db connector and adapt it for Milvus).

**Comment by MiddleSand** [comment]
@cpacker thanks for the advice. I've begun working on a PR for this! :D

**Comment by Bunny15738** [comment]
By any chance is this feature added to letta?
I have ran letta server using docker image and now wanted to integrate milvus as a vector db.
