### ISSUE TITLE
memgpt is very hard to use in a black-on-white terminal window

### ISSUE THREAD

**Issue by cgf1** [letta-ai/letta#710]
It would be nice if there was an option to strip all color from memgpt without having to, e.g., change the TERM environment variable.  The yellow and dim text color scheme that it employs now is almost impossible to read in a terminal window with a white background.

**Comment by cpacker** [comment]
Sorry about this - big oversight! Will test on a white terminal and revise the color palette asap.

**Comment by edt-xx** [comment]
This also is true with a light yellow background, which I find much easier on the eyes than plain white.   Here, white letters on a black background are a bit fuzzy, black letters on the other hand are sharp (due to the lenses used when fixing cataracts).
