### ISSUE TITLE
Make it easy to delete agents with `memgpt delete`

### ISSUE THREAD

**Issue by cpacker** [letta-ai/letta#741]
**Is your feature request related to a problem? Please describe.**

Currently if the user wants to delete an agent (eg to reduce clutter) they have to manually delete folders in `~/.memgpt/agents`.

**Describe the solution you'd like**

Provide a `memgpt delete` command.
- With no args, pulls up a selector
- With args, targets the agent name provided
- Should ask for confirmation before deleting (default to No)

**Comment by sanegaming** [comment]
if the args supported tab completed & ability to do multiple deletions at once would be very nice, doing via api would also be good to specify via an array of names ?
