### ISSUE TITLE
ChromaStorageConnector.get_all() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by clarkandrew** [letta-ai/letta#747]
MemGPT cloned and installed locally on OSX.

There is a bug when trying to use persistent Chroma storage.
```
TypeError: ChromaStorageConnector.get_all() takes 1 positional argument but 2 were given
```

The issue is with this line in `MemGPT/memgpt/memory.py`
```
for passage in list(self.storage.get_all(limit)): 
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

... meanwhile, the get_all method inside ChromaStorageConnector found in `MemGPT/memgpt/connectors/chroma.py` has no limit param:
```
def get_all(self) -> List[Passage]:
```

**Comment by quantumalchemy** [comment]
getting this always with  using quick start / local chroma persistent -- anyone fix this?

**Comment by sarahwooders** [comment]
@quantumalchemy what version are you on, or did you install from source?

**Comment by quantumalchemy** [comment]
211 pip install -U pymemgpt
.. but I see there was a new rel 2 hours ago .. will try tomorrow
