### ISSUE TITLE
Create `Document` table for storing original loaded documents 

### ISSUE THREAD

**Issue by sarahwooders** [letta-ai/letta#770]
We should have a document store, in addition to storing chunked/embedded passages.

**Comment by tombedor** [comment]
Relates to something I've been thinking about - have the agent write "articles" summarizing what it knows about certain topics, and being able to update.

Currently IIUC there's not really a memory consolidation function, where old or outdated memories can be discarded. Eg if today I tell the agent is green but tomorrow I tell it, sorry I made a mistake yesterday, the sky is blue, ideally that old memory would be pruned somehow

**Comment by sarahwooders** [comment]
Now that #708 is merged, this would be a great issue to get a community contribution on. The issue can be broken down in the following todos: 

- [ ] Add a `Document` data type to `data_types.py` that stores the entire original document text and its embedding and metadata
- [ ] Add a `doc_id` field to `Passage` to associate passages with documents 
- [ ] Add a `TableType.DOCUMENTS` to the `agent_store/storage.py` and support document storage for chroma and postgres 
- [ ] In `cli_load.py`, when ingesting passages, also store the associated document and `doc_id`
- [ ] Add a new function that allows the agent to retrieve the document associated with a passage or search over documents
