### ISSUE TITLE
The function set is too confusing for small open-weight language models

### ISSUE THREAD

**Issue by jimlloyd** [letta-ai/letta#794]
**Is your feature request related to a problem? Please describe.**
I think we need to make a significant change to the set of functions the LLM can use for its core functionality, but I will create that issue later. For now, I will just describe the problems we have with the existing functions.

1.  The functions `core_memory_append` and `core_memory_replace` are too similar. The subtle distinctions between them are difficult for small model to grasp.
2. The `core_memory_replace` function is very difficult for anything more complex than replacing "Chad" with "Brad". LLMs are not good at remembering the exact sequence of characters & words in sentences. Even ChatGPT 4 will make mistakes if you ask it to recall a sentence from Core Memory exactly as it appears. It will forget punctuation and it might produce a "summarization" of the sentence. Small LLMs are worse. This means that the `old_content` parameter is extremely difficult for an LLM to use.
3. The parameter `name` for these functions should be named `section`. Just like people, naming matters, and the variable name `name` is not specific enough. I have just spent 20 minutes trying to get MemGPT to correctly call a `core_memory_append` function. It has repeatedly passed the string "section" instead of the string "persona" in the function call. Nothing I have done has been able to get it to correct that mistake. It will acknowledge the mistake, tell me that it understands that it should use the string "persona", and then repeat its mistake!
4. The `conversation_search` and `archival_search` functions are too similar. It is difficult for the LLM to fully understand the distinction between conversation and archive.
5. These smaller models also will hallucinate and think there is a `core_memory_search` function that it should use. I think the LLMs understand the concept of "search" and kind of understand that we have several different kinds of memory stores, so it expects that there should be a search function for each.
6.  The function `core_memory_replace` is not properly documented. The LLM thinks the documentation states that the `name` parameter is optional, and will default to "personal". But when I asked the model to omit the `name` parameter, the error message was that `name` is a required parameter.

**Describe the solution you'd like**
I would to redesign the functions after we settle on a unified storage model. Even if we keep to more modest, incremental changes, we might break some peoples MemGPT configuration by doing something as seemingly innocuous as renaming the `name` parameter to `section`. It shouldn't break anyone's model, but it will if they have tried to work around the problem with explicit instructions in their Core Memory. (But I am probably the only person who has experimented with hacks like that).

**Describe alternatives you've considered**
The proof would not fit in the margin.
Seriously, I have given a lot of thought to alternatives, but this is not the right place for that.

**Additional context**
I will try to capture the conversation in which I tried repeatedly to get the model to call core_memory_append correctly and past it into a comment below.

**Comment by xmwells** [comment]
The model I'm using is Google's Gemini Pro.
When I ask, "Sorry, I've been a bit forgetful lately, could you tell me what it's called?" the model returns that I should call the function core_memory_search. However, this function doesn't actually exist. How can I solve this problem? Do I need to switch models?

logs：
> Enter your message: 不好意思，我最近有点健忘，你能告诉我叫什么吗？
[A[K
Using model google_ai, endpoint: None
Sending request to https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
response = <Response [200]>
response.json = {'candidates': [{'content': {'parts': [{'functionCall': {'name': 'core_memory_search', 'args':
{'inner_thoughts': 'Searching Core Memory for user information... ', 'query': 'First name:', 'request_heartbeat': True}}}],  
'role': 'model'}, 'finishReason': 'STOP', 'index': 0, 'safetyRatings': [{'category': 'HARM_CATEGORY_HARASSMENT',
'probability': 'NEGLIGIBLE'}, {'category': 'HARM_CATEGORY_SEXUALLY_EXPLICIT', 'probability': 'NEGLIGIBLE'}, {'category':     
'HARM_CATEGORY_DANGEROUS_CONTENT', 'probability': 'NEGLIGIBLE'}, {'category': 'HARM_CATEGORY_HATE_SPEECH', 'probability':    
'NEGLIGIBLE'}]}]}
Function call message: <memgpt.data_types.Message object at 0x0000028B7667FF50>
💭 Searching Core Memory for user information... 
Request to call function core_memory_search with tool_call_id: af80ce28-57bf-478b-9822-b3c66
⚡🔴 [function] Error: No function named core_memory_search

**Comment by xmwells** [comment]
It should be fine to look for the core memory, but why can't I see any method for searching the core memory?

**Comment by xmwells** [comment]
It should be fine to look for the core memory, but why can't I see any function for searching the core memory?
