### ISSUE TITLE
Producing errant message key: "mesaage" instead of "message"

### ISSUE THREAD

**Issue by sgjohnson1981** [letta-ai/letta#807]
**Describe the bug**
Is this a bad model or something else? It seems to produce "mesaage" key instead of "message" key, so send_message won't work.

```
Loading default settings from 'simple'
Found completion settings file 'C:\Users\Dell T3500\.memgpt\settings\completions_api_settings.json', loading it...
'C:\Users\Dell T3500\.memgpt\settings\completions_api_settings.json' was empty, ignoring...
JSON API response:
{'content': ' "send_message",\n  "params": {\n     "inner_thoughts": "I don\'t have a physical body to connect to the internet, but I do have access to 
vast amounts of data and knowledge.",\n     "mesaage": "While I don\'t physically browse the web like you do, I\'m connected to an extensive database   
that contains up-to-date information from various sources."\n ', 'generation_settings': {'frequency_penalty': 0.0, 'grammar': '', 'ignore_eos': False,  
'logit_bias': [], 'min_p': 0.05000000074505806, 'mirostat': 0, 'mirostat_eta': 0.10000000149011612, 'mirostat_tau': 5.0, 'model':
'.\\models\\dolphin-2.6-mistral-7b-dpo.Q5_K_M_ngl33.gguf', 'n_ctx': 8192, 'n_keep': 0, 'n_predict': -1, 'n_probs': 0, 'penalize_nl': True,
'penalty_prompt_tokens': [], 'presence_penalty': 0.0, 'repeat_last_n': 64, 'repeat_penalty': 1.100000023841858, 'seed': 4294967295, 'stop': ['\nUSER:', 
'\nASSISTANT:', '\nFUNCTION RETURN:', '\nUSER', '\nASSISTANT', '\nFUNCTION RETURN', '\nFUNCTION', '\nFUNC', '<|im_start|>', '<|im_end|>', '<|im_sep|>', 
'\n### ', '\n#', '  }\n}\n'], 'stream': False, 'temperature': 0.800000011920929, 'tfs_z': 1.0, 'top_k': 40, 'top_p': 0.949999988079071, 'typical_p':    
1.0, 'use_penalty_prompt_tokens': False}, 'model': '.\\models\\dolphin-2.6-mistral-7b-dpo.Q5_K_M_ngl33.gguf', 'prompt': 
```

**Please describe your setup**

- [ ] MemGPT version
  - What is the output of `memgpt version`? (eg "0.2.4")
  0.2.11
- [ ] How did you install memgpt?
  - `pip install pymemgpt`? `pip install pymemgpt-nightly`? `git clone`?
  via pip install pymemgpt[local]
- [ ] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?
  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal)
  Windows 10; memgpt run is in VS Code terminal, llama.cpp's server.exe is running in command prompt 

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`) **See above**
- [ ] The local LLM backend you are using (web UI? LM Studio?) **See above**
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?) **RTX 2070 Super**

**Comment by AdamScoggins** [comment]
I found this happens to me when I don't use Q8. Possibly related to https://github.com/cpacker/MemGPT/issues/794

**Comment by sgjohnson1981** [comment]
> I found this happens to me when I don't use Q8. Possibly related to #794

Interesting. I would have thought spelling correctly would be easier than not hallucinating a key that doesn't exist. I was suspecting "mesaage" was some misspelling either in the code or in its training data.
