### ISSUE TITLE
0.2.12: load directory with hugging-face embeddings fails

### ISSUE THREAD

**Issue by jimlloyd** [letta-ai/letta#811]
**Describe the bug**
I am trying to use hugging-face embeddings with an embedding model that has 1024 dimensions.
When I run `memgpt load directory --recursive ...` it fails with an assertion (lines 123..125 of cli_load.py):

```
        assert (
            len(node.embedding) == user.default_embedding_config.embedding_dim
        ), f"Expected embedding dimension {user.default_embedding_config.embedding_dim}, got {len(node.embedding)}: {node.embedding}"
```

It expected 1024 dimensions, got 384. I think this is because of the fallback that I put into place "at the last minute" in order to merge my PR that partly fixed `memgpt load`.

If I instead use local embeddings then everything works.

**Please describe your setup**

- [ ] MemGPT version
  0.2.12

- [ ] How did you install memgpt?
poetry

- [ ] Describe your setup
MacOS Sonoma
Terminal

**Screenshots**
N/A

**Additional context**
N/A

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by sarahwooders** [comment]
I believe this is the same issue as #814?
