### ISSUE TITLE
0.2.12: `memgpt run` fails if new agent name coincidentally is a duplictate

### ISSUE THREAD

**Issue by jimlloyd** [letta-ai/letta#813]
**Describe the bug**

```
Failed to create agent from provided information:
Agent with name AngryReindeer already exists
```

**Please describe your setup**

- [ ] MemGPT version
0.2.12

- [ ] How did you install memgpt?
poetry

- [ ] Describe your setup
MacOS Sonoma / Terminal

**Screenshots**
N/A

**Additional context**
N/A

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by sarahwooders** [comment]
@cpacker is this a result of the random name generation we're using? like its not random enough..?
