### ISSUE TITLE
TypeError: LocalStateManager.__init__() got an unexpected keyword argument 'agent_config'

### ISSUE THREAD

**Issue by mongolu** [letta-ai/letta#817]
**Describe the bug**
I'm trying to run the code from autogen from this file:
`memgpt/autogen/examples/memgpt_coder_autogen.ipynb`
In file `memgpt/autogen/memgpt_agent.py` at line  170, i think it should've been 
`"agent_state": agent_config,` .

**LOGS:**
```
Traceback (most recent call last):
  File "/LLMmodels/autogen/ytest.py", line 75, in <module>
    coder = create_memgpt_autogen_agent_from_config(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/MemGPT/memgpt/autogen/memgpt_agent.py", line 95, in create_memgpt_autogen_agent_from_config
    autogen_memgpt_agent = create_autogen_memgpt_agent(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/MemGPT/memgpt/autogen/memgpt_agent.py", line 172, in create_autogen_memgpt_agent
    persistence_manager = LocalStateManager(**persistence_manager_kwargs) if persistence_manager is None else persistence_manager
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LocalStateManager.__init__() got an unexpected keyword argument 'agent_config'
```

**Please describe your setup**

- [x] MemGPT version
  - What is the output of `memgpt version`? (eg "0.2.4") `0.2.12`
- [x] How did you install memgpt?
  - `pip install pymemgpt`? `pip install pymemgpt-nightly`? `git clone`? `git clone`
- [x] Describe your setup
  - What's your OS (Windows/MacOS/Linux)? Linux
  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal) `terminal`

**Screenshots**

**Additional context**

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by cpacker** [comment]
Hey @mongolu , sorry for the delay! This is basically a version issue - the latest code on this github repo is for the eventual 0.2.12 release, but the AutoGen part of the repo has not been updated yet so it won't work until #787 is finished.

If you want to use AutoGen, you should use 0.2.11. You can do this by grabbing the pip package (`pip install pymemgpt` or `pip install pymemgpt==0.2.11`), or by cloning the github repo then doing `git checkout 0.2.11`).
