### ISSUE TITLE
[Chat UI] Agent Creation Dropdown Inputs

### ISSUE THREAD

**Issue by arduenify** [letta-ai/letta#897]
**Is your feature request related to a problem? Please describe.**
Currently, in the Chat UI for creating an agent, there are four text input fields: 'name', 'human', 'persona', and 'model'. The issue is that these fields require manual input every time, which can be time-consuming and prone to inconsistency, especially if there are predefined, commonly used values that could be selected. 

![image](https://github.com/cpacker/MemGPT/assets/17145951/0542ed32-08dd-4964-84de-624c9d3ff745)

**Describe the solution you'd like**
I propose to enhance these text input fields by converting them into dropdown menus that populate with values retrieved from the database. This would streamline the agent creation process by allowing users to select from a list of predefined, frequently used options. Additionally, to maintain flexibility, the fields should also support manual text input for cases where the desired value is not in the dropdown. This dual approach (dropdown with a manual input option) would cater to both common and unique agent creation scenarios.

**Describe alternatives you've considered**
An alternative could be the implementation of an auto-complete feature for these text fields. As users begin to type, suggestions based on existing database entries could appear. Although this might not be as user-friendly for discovering available options compared to dropdown menus.

**Additional context**
The change requires backend support for fetching the relevant data to populate the dropdowns, as well as frontend modifications for the UI change.

This will require 2 PRs: One for React and one for the Rest API.

**Comment by cpacker** [comment]
(reopening since the backend needs to be updated for non-placeholder, assigned to @cpacker)
