### ISSUE TITLE
[Chat UI] Edit & Delete Agents

### ISSUE THREAD

**Issue by arduenify** [letta-ai/letta#914]
**Is your feature request related to a problem? Please describe.**
Currently, in the Chat UI, there is no functionality to edit or delete agents. This feature will allow said functionality.

**Describe the solution you'd like**

- [ ] Implement functionality to edit an agent
- [ ] Implement functionality to delete an agent (DialogAlert to confirm deletion)
- [ ] More diverse information when viewing agents (model, persona, human)
- [ ] Enhance the agent creation form to dynamically populate default settings and available models, in line with the changes proposed in issue #920 

**Describe alternatives you've considered**
I have not considered any alternatives, as this is fairly straightforward.

**Additional context**
This is somewhat related to #897, which is solved by PR #899, allowing agents to be added based on the information retrieved from the Sync Server. 

I will work on the PR for this. If you don't mind, please assign me to this issue, and let me know if there are any specific features you want me to include, or if there is anything else you would like to incorporate into this issue. @cpacker @goetzrobin

**Comment by cpacker** [comment]
I think this is great! I was actually thinking about this when I added the REST delete agent endpoint: https://github.com/cpacker/MemGPT/pull/882

Maybe you can include a "trash" or "x" icon inside the tile view for each agent? And when you click it, it asks "do you want to delete" or something, then on confirmation will send the DELETE request and refresh the tiles? Just a suggestion for the UI flow, @goetzrobin @arduenify you may have other opinions.

<img width="294" alt="image" src="https://github.com/cpacker/MemGPT/assets/5475622/4f00902e-2a2f-4926-a37c-e088d3b1e05a">
