### ISSUE TITLE
Fix all typing errors

### ISSUE THREAD

**Issue by cpacker** [letta-ai/letta#916]
Currently there are a fair amount of typing warnings/errors in the project:

- [x] Add pyright to github actions
- [ ] Do a full pass over the codebase to correct pyright errors
- [ ] Disable `continue on error` on github actions once pyright is passing

Merge incremental PRs ASAP to avoid merge conflicts. Close issue once:

- [ ] pyright passes

**Comment by dlaliberte** [comment]
I'd like to get very familiar with the MemGPT code, so this might be a good way to do it.  I'm still fairly new to Python and pyright, but have decades of experience as a software engineer.
