### ISSUE TITLE
Allowing External tools to not force inner monologue ?

### ISSUE THREAD

**Issue by CUexter** [letta-ai/letta#951]
**Is your feature request related to a problem? Please describe.**
I am struggling to integrate external tools in the system. Here is what I tried: 
```python
def send_emotion(self, emotion: str):
    """
    This function is used to display your inner emotion to the user.
    Determine the appropriate emotion and send it to the function.

    Args:
        emotion (str): The emotion that is suitable to displayed for the conversation. The available emotion are only ["neutral", "happy", "sad"].
    Returns:
        bool: Whether the user received the emotion sent
    """

    print(emotion)
    return True
```
This looks simple, and of course it works. However I want my agent to always response with both emotion and send_message. So I modified the system_prompts and the presets.
However this is the response:
![image](https://github.com/cpacker/MemGPT/assets/79507956/5c989e09-a0d0-4c22-b122-ac51bf5d2120)

It would be perfect if the None returned could be skipped. 

**Describe the solution you'd like**
Does the system prompt the LLM to respond to a function call, even if it is not returning anything meaningful ? Is there a way to just ignore the None

**Describe alternatives you've considered**
Currently my fix is just to omit the assert function in line 249 of the data_types.py

It still displays None but apparently this allowed the conversation to continue.

**Comment by CUexter** [comment]
I am not sure whether this is a bug or a feature request ? Would like to know more how the function calling work ? maybe feature request for better docs ?

**Comment by tombedor** [comment]
I've gotten something similar and hacked a fix here: https://github.com/cpacker/MemGPT/commit/2c60cd2927a4d87c1865c8e985802a7556ef8f0e#diff-e04e7264fdf24a55561ca8f31b8bd247e74f392682c13d635decdaf244a6def6R121-R124

but possibly the empty request being sent to open is really the issue

**Comment by tombedor** [comment]
the internal monologue does not seem to work well with function calls currently, I think the ideal behavior is that the agent receives a system message notifying it that the function has been called (or perhaps, just no agent loop runs for the function call?

**Comment by CUexter** [comment]
agree i think we should allow the agent to skip past it
