### ISSUE TITLE
Add support for Python 3.12

### ISSUE THREAD

**Issue by captain828** [letta-ai/letta#954]
**Is your feature request related to a problem? Please describe.**
Can't run MemGPT on a project using Python 3.12.

**Describe the solution you'd like**
Add support for Python 3.12.

**Describe alternatives you've considered**
I understand downgrading to Python 3.11 is a workaround.

**Additional context**
I understand the complexity of supporting 3.12 at this time due to some libraries not yet being generally available for 3.12, so I see this issue as more of tracking when support has been added for 3.12.

**Comment by sarahwooders** [comment]
Yes we should support 3.12 - I believe there is some error that happens with 3.12 that needs to be resolved.

**Comment by Shikharhacks007** [comment]
Is there any update on the error for support for Python 3.12.
I am running it on windows and there seems to be build fail for a few libraries.
